//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuotationGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QuotRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuotRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuotationGenerator.QuotRes", typeof(QuotRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Многие люди предпочитают иметь немножко денег и немножко счастья, чем опозориться, рискнув погнаться за всем, что может предложить жизнь.
        ///Роберт Кийосаки
        ////
        ///Если бы у вас ничего не было - ни денег, ни работы, ни еды, ни жилья - что бы вы стали делать? 
        ///Роберт Кийосаки
        ////
        ///Нужно сделать выбор между свободой и безопасностью. Свобода требует смелости и силы, а если у человека их нет, он теряет свободу.
        ///Роберт Кийосаки
        ////
        ///Оправдания - это ложь, которую вы говорите самим себе. Прекратите хныкать, жаловать [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bogatstvo {
            get {
                return ResourceManager.GetString("bogatstvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы любим до первой измены и ненавидим до первого поцелуя.
        ////
        ///Влюбился - это когда стоишь, как идиот около женского туалета, с женской сумкой и рад.
        ////
        ///Лучшее в отношениях - это их не выяснять... Лучшее в любви - это ею заниматься...
        ////
        ///Мозг - самый удивительный орган. Он способен работать 24 часа в сутки, 365 дней в году, с момента вашего рождения и ровно до тех пор... пока вы не влюбитесь.
        ////
        ///Любовь - это когда ты закрываешь глаза на недостатки партнера, открываешь... хоп - а уже дети!
        ////
        ///Иногда, чтоб [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lyubov {
            get {
                return ResourceManager.GetString("lyubov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я этого хочу. Значит, это будет.  
        ///Генри Форд
        ////
        ///Урок, который я извлек и которому следую всю жизнь, состоял в том, что надо пытаться, и пытаться, и опять пытаться — но никогда не сдаваться!  
        ///Ричард Бренсон
        ////
        ///Наш большой недостаток в том, что мы слишком быстро опускаем руки. Наиболее верный путь к успеху – все время пробовать еще один раз. 
        ///Томас Эдисон
        ////
        ///Для успеха не надо быть умнее других, надо просто быть на день быстрее большинства.  
        ///Лео Сцилард
        ////
        ///Самым важным слагаемым формулы успеха явля [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string uspekh {
            get {
                return ResourceManager.GetString("uspekh", resourceCulture);
            }
        }
    }
}
