//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarumaResourcesPortable.LocalizationResources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DarumaResourcesPortable.LocalizationResources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сжечь.
        /// </summary>
        public static string Burn {
            get {
                return ResourceManager.GetString("Burn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дарума.
        /// </summary>
        public static string Daruma {
            get {
                return ResourceManager.GetString("Daruma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДАРУМА.
        /// </summary>
        public static string Daruma_Up_Case {
            get {
                return ResourceManager.GetString("Daruma_Up_Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Японская традиционная кукла-неваляшка приносит счастье и исполняет желания. Нарисуй зрачок Даруме и запиши свою мечту. Когда мечта сбудется, закрась и второй зрачок Дарумы. 
        ///Коснись Дарумы и проведи пальцем вправо или влево, чтобы пообщаться с Дарумой.
        ///
        ///Дарума рассказывает тебе притчу. Мужик в троллейбусе едет и думает: «Жена капризная, друзья вечно заняты, жизнь не интересная». За спиной стоит Ангел, записывает в блокнот и думает:«Какие странные желания, а главное одни и те же каждый день! Но ничего не  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DarumaInfo {
            get {
                return ResourceManager.GetString("DarumaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустые.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пусто, придумайте желание.
        /// </summary>
        public static string EmptyWishTextBox {
            get {
                return ResourceManager.GetString("EmptyWishTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполненные.
        /// </summary>
        public static string Executed {
            get {
                return ResourceManager.GetString("Executed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Истекшие.
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В избранное.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохраненные цитаты.
        /// </summary>
        public static string FavoritQuotations {
            get {
                return ResourceManager.GetString("FavoritQuotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вперед.
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дружба.
        /// </summary>
        public static string Friendship {
            get {
                return ResourceManager.GetString("Friendship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смешное.
        /// </summary>
        public static string Funny {
            get {
                return ResourceManager.GetString("Funny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здоровье.
        /// </summary>
        public static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К списку.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инфо.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точно удалить?.
        /// </summary>
        public static string IsDelete {
            get {
                return ResourceManager.GetString("IsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Желание исполнилоcь?.
        /// </summary>
        public static string IsWishComeTrue {
            get {
                return ResourceManager.GetString("IsWishComeTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Любовь.
        /// </summary>
        public static string Love {
            get {
                return ResourceManager.GetString("Love", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удача.
        /// </summary>
        public static string Luck {
            get {
                return ResourceManager.GetString("Luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почту.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загаданные.
        /// </summary>
        public static string Maked {
            get {
                return ResourceManager.GetString("Maked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщения.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрепить.
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цитата.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru-RU.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Богатство.
        /// </summary>
        public static string Rich {
            get {
                return ResourceManager.GetString("Rich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поделиться.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПОДЕЛИТЬСЯ ЧЕРЕЗ.
        /// </summary>
        public static string ShareBy_Up_Case {
            get {
                return ResourceManager.GetString("ShareBy_Up_Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Социальные сети.
        /// </summary>
        public static string SocialNetwork {
            get {
                return ResourceManager.GetString("SocialNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коснись и загадай.
        /// </summary>
        public static string TouchAndWish {
            get {
                return ResourceManager.GetString("TouchAndWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Буфер обмена.
        /// </summary>
        public static string ToСlipboard {
            get {
                return ResourceManager.GetString("ToСlipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открепить.
        /// </summary>
        public static string Unpin {
            get {
                return ResourceManager.GetString("Unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загадать.
        /// </summary>
        public static string WishButton {
            get {
                return ResourceManager.GetString("WishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнение желания.
        /// </summary>
        public static string WishComeTrue {
            get {
                return ResourceManager.GetString("WishComeTrue", resourceCulture);
            }
        }
    }
}
