//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarumaResourcesPortable.LocalizationResources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CitationLocalizationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CitationLocalizationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DarumaResourcesPortable.LocalizationResources.CitationLocalizationResources", typeof(CitationLocalizationResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обходя разложенные грабли - ты теряешь драгоценный опыт!.
        /// </summary>
        public static string Funy_0 {
            get {
                return ResourceManager.GetString("Funy_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жизнь удалась, если коньяк, который мы пьем, старше женщин, с которыми мы спим..
        /// </summary>
        public static string Funy_1 {
            get {
                return ResourceManager.GetString("Funy_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если ты хочешь выйти замуж за умного, красивого и богатого, придется выходить замуж три раза..
        /// </summary>
        public static string Funy_10 {
            get {
                return ResourceManager.GetString("Funy_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мужчине достаточно быть чуть красивее обезьяны..
        /// </summary>
        public static string Funy_11 {
            get {
                return ResourceManager.GetString("Funy_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шутки шутками, но могут быть и дети..
        /// </summary>
        public static string Funy_12 {
            get {
                return ResourceManager.GetString("Funy_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Умна та женщина, в обществе которой можно вести себя как угодно глупо..
        /// </summary>
        public static string Funy_2 {
            get {
                return ResourceManager.GetString("Funy_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одиночество - это когда ты всегда знаешь, где лежат твои вещи..
        /// </summary>
        public static string Funy_3 {
            get {
                return ResourceManager.GetString("Funy_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Второй брак - это победа надежды над здравым смыслом..
        /// </summary>
        public static string Funy_4 {
            get {
                return ResourceManager.GetString("Funy_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ничего страшного если над тобой смеются... Гораздо хуже, когда над тобой плачут....
        /// </summary>
        public static string Funy_5 {
            get {
                return ResourceManager.GetString("Funy_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Утро - это такая часть суток, когда завидуешь безработным....
        /// </summary>
        public static string Funy_6 {
            get {
                return ResourceManager.GetString("Funy_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детская мудрость: если мама смеется над остротами папы, значит, в доме гости..
        /// </summary>
        public static string Funy_7 {
            get {
                return ResourceManager.GetString("Funy_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если женщина вас обманывает, значит, вы ей небезразличны.
        /// </summary>
        public static string Funy_8 {
            get {
                return ResourceManager.GetString("Funy_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Девушки бывают или умные, или красивые..
        /// </summary>
        public static string Funy_9 {
            get {
                return ResourceManager.GetString("Funy_9", resourceCulture);
            }
        }
    }
}
