//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarumaResourcesPortable.LocalizationResources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Friendship {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Friendship() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DarumaResourcesPortable.LocalizationResources.Friendship", typeof(Friendship).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не ставь недруга овцою, а ставь его волком..
        /// </summary>
        public static string Friendship_0 {
            get {
                return ResourceManager.GetString("Friendship_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добрый друг лучше ста родственников..
        /// </summary>
        public static string Friendship_1 {
            get {
                return ResourceManager.GetString("Friendship_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все пройдет, одна правда останется..
        /// </summary>
        public static string Friendship_10 {
            get {
                return ResourceManager.GetString("Friendship_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы с тобой, как рыба с водой..
        /// </summary>
        public static string Friendship_100 {
            get {
                return ResourceManager.GetString("Friendship_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Надо пуд соли вместе съесть, чтобы друга узнать..
        /// </summary>
        public static string Friendship_101 {
            get {
                return ResourceManager.GetString("Friendship_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не бойся врага умного, бойся друга глупого..
        /// </summary>
        public static string Friendship_102 {
            get {
                return ResourceManager.GetString("Friendship_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не сошлись обычаем, не бывать дружбе..
        /// </summary>
        public static string Friendship_103 {
            get {
                return ResourceManager.GetString("Friendship_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не узнавай друга в три дня, узнай в три года..
        /// </summary>
        public static string Friendship_104 {
            get {
                return ResourceManager.GetString("Friendship_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недруг поддакивает, а друг спорит.
        /// </summary>
        public static string Friendship_105 {
            get {
                return ResourceManager.GetString("Friendship_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новых друзей наживай, а старых не утрачивай..
        /// </summary>
        public static string Friendship_106 {
            get {
                return ResourceManager.GetString("Friendship_106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Один в поле не воин.
        /// </summary>
        public static string Friendship_107 {
            get {
                return ResourceManager.GetString("Friendship_107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рыбак рыбака видит издалека.
        /// </summary>
        public static string Friendship_108 {
            get {
                return ResourceManager.GetString("Friendship_108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С кем поведешься, от того и наберешься..
        /// </summary>
        public static string Friendship_109 {
            get {
                return ResourceManager.GetString("Friendship_109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Волк — хищник по природе, а человек — по зависти..
        /// </summary>
        public static string Friendship_11 {
            get {
                return ResourceManager.GetString("Friendship_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С кем хлеб-соль водишь, на того и походишь.
        /// </summary>
        public static string Friendship_110 {
            get {
                return ResourceManager.GetString("Friendship_110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скажи мне, кто твой друг, и я скажу тебе, кто ты..
        /// </summary>
        public static string Friendship_111 {
            get {
                return ResourceManager.GetString("Friendship_111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У друга пить воду лучше неприятельского меду..
        /// </summary>
        public static string Friendship_112 {
            get {
                return ResourceManager.GetString("Friendship_112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хороший друг в лицо ругает, а за глаза хвалит.
        /// </summary>
        public static string Friendship_113 {
            get {
                return ResourceManager.GetString("Friendship_113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дружно — не грузно, а врозь — хоть брось.
        /// </summary>
        public static string Friendship_114 {
            get {
                return ResourceManager.GetString("Friendship_114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Согласного стада и волк не берет..
        /// </summary>
        public static string Friendship_115 {
            get {
                return ResourceManager.GetString("Friendship_115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По прутику всю метлу переломить можно..
        /// </summary>
        public static string Friendship_116 {
            get {
                return ResourceManager.GetString("Friendship_116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На людях и смерть красна..
        /// </summary>
        public static string Friendship_117 {
            get {
                return ResourceManager.GetString("Friendship_117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Две головни и в поле курятся, а одна и в печи гаснет..
        /// </summary>
        public static string Friendship_118 {
            get {
                return ResourceManager.GetString("Friendship_118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По капельке — море, по былинке — стог, по зернышку — ворох..
        /// </summary>
        public static string Friendship_119 {
            get {
                return ResourceManager.GetString("Friendship_119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доносчику первый кнут..
        /// </summary>
        public static string Friendship_12 {
            get {
                return ResourceManager.GetString("Friendship_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В мире жить — с миром жить..
        /// </summary>
        public static string Friendship_120 {
            get {
                return ResourceManager.GetString("Friendship_120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На что и клад, когда дети идут в лад.
        /// </summary>
        public static string Friendship_121 {
            get {
                return ResourceManager.GetString("Friendship_121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всякая ссора красна мировою..
        /// </summary>
        public static string Friendship_122 {
            get {
                return ResourceManager.GetString("Friendship_122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дракою прав не будешь..
        /// </summary>
        public static string Friendship_123 {
            get {
                return ResourceManager.GetString("Friendship_123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Семеро одного не ждут..
        /// </summary>
        public static string Friendship_124 {
            get {
                return ResourceManager.GetString("Friendship_124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to То не страх, что вместях, а сунься-ка один..
        /// </summary>
        public static string Friendship_125 {
            get {
                return ResourceManager.GetString("Friendship_125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Был бы запевала, а подголоски найдутся..
        /// </summary>
        public static string Friendship_126 {
            get {
                return ResourceManager.GetString("Friendship_126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одна пчела не много меду натаскает..
        /// </summary>
        public static string Friendship_127 {
            get {
                return ResourceManager.GetString("Friendship_127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одной рукой и узла не завяжешь..
        /// </summary>
        public static string Friendship_128 {
            get {
                return ResourceManager.GetString("Friendship_128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Двое в поле воюют, а один и дома горюет..
        /// </summary>
        public static string Friendship_129 {
            get {
                return ResourceManager.GetString("Friendship_129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Был бы друг, найдется и досуг..
        /// </summary>
        public static string Friendship_13 {
            get {
                return ResourceManager.GetString("Friendship_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Беда не там страшна, где есть друзья,.
        /// </summary>
        public static string Friendship_130 {
            get {
                return ResourceManager.GetString("Friendship_130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Один и в каше загинет..
        /// </summary>
        public static string Friendship_131 {
            get {
                return ResourceManager.GetString("Friendship_131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сам себе на радость никто не живет..
        /// </summary>
        public static string Friendship_132 {
            get {
                return ResourceManager.GetString("Friendship_132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Глуп совсем, кто не знается ни с кем..
        /// </summary>
        public static string Friendship_133 {
            get {
                return ResourceManager.GetString("Friendship_133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пять перстов, да все одна рука..
        /// </summary>
        public static string Friendship_134 {
            get {
                return ResourceManager.GetString("Friendship_134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доброе братство дороже всякого богатства..
        /// </summary>
        public static string Friendship_135 {
            get {
                return ResourceManager.GetString("Friendship_135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друг за дружку держаться — ничего не бояться.
        /// </summary>
        public static string Friendship_136 {
            get {
                return ResourceManager.GetString("Friendship_136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Артелью хорошо и недруга бить..
        /// </summary>
        public static string Friendship_137 {
            get {
                return ResourceManager.GetString("Friendship_137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Артель дружбой крепка..
        /// </summary>
        public static string Friendship_138 {
            get {
                return ResourceManager.GetString("Friendship_138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Семеро — не один, в обиду не дадим..
        /// </summary>
        public static string Friendship_139 {
            get {
                return ResourceManager.GetString("Friendship_139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучше умереть возле друга, чем жить у своего врага..
        /// </summary>
        public static string Friendship_14 {
            get {
                return ResourceManager.GetString("Friendship_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Человек к человеку — глядишь и толпа,.
        /// </summary>
        public static string Friendship_140 {
            get {
                return ResourceManager.GetString("Friendship_140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вместе мокли, вместе сохли..
        /// </summary>
        public static string Friendship_141 {
            get {
                return ResourceManager.GetString("Friendship_141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слушай, рябина, что лес говорит..
        /// </summary>
        public static string Friendship_142 {
            get {
                return ResourceManager.GetString("Friendship_142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Артельный котел гуще кипит..
        /// </summary>
        public static string Friendship_143 {
            get {
                return ResourceManager.GetString("Friendship_143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все за бечеву — скорее переедешь..
        /// </summary>
        public static string Friendship_144 {
            get {
                return ResourceManager.GetString("Friendship_144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дружные сороки и гуся утащат..
        /// </summary>
        public static string Friendship_145 {
            get {
                return ResourceManager.GetString("Friendship_145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Служи миру и будешь сыт..
        /// </summary>
        public static string Friendship_146 {
            get {
                return ResourceManager.GetString("Friendship_146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С миру по нитке, голому рубашка..
        /// </summary>
        public static string Friendship_147 {
            get {
                return ResourceManager.GetString("Friendship_147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свет не без добрых людей..
        /// </summary>
        public static string Friendship_148 {
            get {
                return ResourceManager.GetString("Friendship_148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не связанный сноп — солома..
        /// </summary>
        public static string Friendship_149 {
            get {
                return ResourceManager.GetString("Friendship_149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Худой мир лучше доброй ссоры.
        /// </summary>
        public static string Friendship_15 {
            get {
                return ResourceManager.GetString("Friendship_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сам пропадай, а товарища выручай..
        /// </summary>
        public static string Friendship_150 {
            get {
                return ResourceManager.GetString("Friendship_150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не мил и свет, когда друга нет..
        /// </summary>
        public static string Friendship_151 {
            get {
                return ResourceManager.GetString("Friendship_151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По товарищам и слава..
        /// </summary>
        public static string Friendship_152 {
            get {
                return ResourceManager.GetString("Friendship_152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не узнавай друга в три дня, узнавай в три года..
        /// </summary>
        public static string Friendship_153 {
            get {
                return ResourceManager.GetString("Friendship_153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конь узнается при горе, а друг при беде..
        /// </summary>
        public static string Friendship_154 {
            get {
                return ResourceManager.GetString("Friendship_154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друг узнается при рати и при беде..
        /// </summary>
        public static string Friendship_155 {
            get {
                return ResourceManager.GetString("Friendship_155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друзья прямые, что братья родные..
        /// </summary>
        public static string Friendship_156 {
            get {
                return ResourceManager.GetString("Friendship_156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для друга всё не туго..
        /// </summary>
        public static string Friendship_157 {
            get {
                return ResourceManager.GetString("Friendship_157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дружбу водить, так себя не щадить..
        /// </summary>
        public static string Friendship_158 {
            get {
                return ResourceManager.GetString("Friendship_158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дружба дружбе рознь, а иную хоть брось..
        /// </summary>
        public static string Friendship_159 {
            get {
                return ResourceManager.GetString("Friendship_159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друг за друга держаться - ничего не бояться..
        /// </summary>
        public static string Friendship_16 {
            get {
                return ResourceManager.GetString("Friendship_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Живи для людей, поживут люди для тебя..
        /// </summary>
        public static string Friendship_160 {
            get {
                return ResourceManager.GetString("Friendship_160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дружба да братство дороже всякого богатства..
        /// </summary>
        public static string Friendship_161 {
            get {
                return ResourceManager.GetString("Friendship_161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больше той любви не бывает, коль друг за друга погибает..
        /// </summary>
        public static string Friendship_162 {
            get {
                return ResourceManager.GetString("Friendship_162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не поживши вместе, друга не узнаешь..
        /// </summary>
        public static string Friendship_163 {
            get {
                return ResourceManager.GetString("Friendship_163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друзья познаются в беде.
        /// </summary>
        public static string Friendship_164 {
            get {
                return ResourceManager.GetString("Friendship_164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дружба, что стекло; сломаешь — не починишь..
        /// </summary>
        public static string Friendship_165 {
            get {
                return ResourceManager.GetString("Friendship_165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плохи друзья на полчаса..
        /// </summary>
        public static string Friendship_166 {
            get {
                return ResourceManager.GetString("Friendship_166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный друг опаснее врага..
        /// </summary>
        public static string Friendship_167 {
            get {
                return ResourceManager.GetString("Friendship_167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто любит лгать, того нельзя в друзья брать..
        /// </summary>
        public static string Friendship_168 {
            get {
                return ResourceManager.GetString("Friendship_168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друг спорит, а враг поддакивает..
        /// </summary>
        public static string Friendship_169 {
            get {
                return ResourceManager.GetString("Friendship_169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не бей в чужие ворота плетью, не ударили бы в твои дубиною..
        /// </summary>
        public static string Friendship_17 {
            get {
                return ResourceManager.GetString("Friendship_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дружбу за деньги не купишь..
        /// </summary>
        public static string Friendship_170 {
            get {
                return ResourceManager.GetString("Friendship_170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дружба как стекло: разобьешь не сложишь..
        /// </summary>
        public static string Friendship_171 {
            get {
                return ResourceManager.GetString("Friendship_171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Человек без друзей, что дерево без корней..
        /// </summary>
        public static string Friendship_172 {
            get {
                return ResourceManager.GetString("Friendship_172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучше жить в тесноте, чем в обиде..
        /// </summary>
        public static string Friendship_173 {
            get {
                return ResourceManager.GetString("Friendship_173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постучит беда в окошко -.
        /// </summary>
        public static string Friendship_174 {
            get {
                return ResourceManager.GetString("Friendship_174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подружится собака с кошкой..
        /// </summary>
        public static string Friendship_175 {
            get {
                return ResourceManager.GetString("Friendship_175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не хвались другом в три дня,.
        /// </summary>
        public static string Friendship_176 {
            get {
                return ResourceManager.GetString("Friendship_176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to А хвались в три года..
        /// </summary>
        public static string Friendship_177 {
            get {
                return ResourceManager.GetString("Friendship_177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На службе нет дружбы..
        /// </summary>
        public static string Friendship_178 {
            get {
                return ResourceManager.GetString("Friendship_178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бывший друг - злейший враг..
        /// </summary>
        public static string Friendship_179 {
            get {
                return ResourceManager.GetString("Friendship_179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вешний лед обманчив, а новый друг не надежен..
        /// </summary>
        public static string Friendship_18 {
            get {
                return ResourceManager.GetString("Friendship_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучше честный враг, чем коварный друг..
        /// </summary>
        public static string Friendship_180 {
            get {
                return ResourceManager.GetString("Friendship_180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Живи, не скупись, с друзьями делись..
        /// </summary>
        public static string Friendship_19 {
            get {
                return ResourceManager.GetString("Friendship_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как аукнется, так и откликнется.
        /// </summary>
        public static string Friendship_2 {
            get {
                return ResourceManager.GetString("Friendship_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Много добра в кувшине, да головой в него не пролезешь..
        /// </summary>
        public static string Friendship_20 {
            get {
                return ResourceManager.GetString("Friendship_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Два друга - мороз да вьюга..
        /// </summary>
        public static string Friendship_21 {
            get {
                return ResourceManager.GetString("Friendship_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друг верен во всем измерен..
        /// </summary>
        public static string Friendship_22 {
            get {
                return ResourceManager.GetString("Friendship_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лжец - всегда неверный друг, оболжет тебя вокруг..
        /// </summary>
        public static string Friendship_23 {
            get {
                return ResourceManager.GetString("Friendship_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кому мир недорог, тот нам и ворог..
        /// </summary>
        public static string Friendship_24 {
            get {
                return ResourceManager.GetString("Friendship_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правда всего дороже..
        /// </summary>
        public static string Friendship_25 {
            get {
                return ResourceManager.GetString("Friendship_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дружно за мир стоять — войне не бывать..
        /// </summary>
        public static string Friendship_26 {
            get {
                return ResourceManager.GetString("Friendship_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь друг, да не вдруг..
        /// </summary>
        public static string Friendship_27 {
            get {
                return ResourceManager.GetString("Friendship_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ласковый роток да чистые руки по всей земле обведут..
        /// </summary>
        public static string Friendship_28 {
            get {
                return ResourceManager.GetString("Friendship_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Держись друга старого, а дома нового.
        /// </summary>
        public static string Friendship_29 {
            get {
                return ResourceManager.GetString("Friendship_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто друг себе, а кто и недруг..
        /// </summary>
        public static string Friendship_3 {
            get {
                return ResourceManager.GetString("Friendship_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Надсаженный конь, надломленный лук, замиренный друг - ненадежны..
        /// </summary>
        public static string Friendship_30 {
            get {
                return ResourceManager.GetString("Friendship_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правду говорить - друга не нажить..
        /// </summary>
        public static string Friendship_31 {
            get {
                return ResourceManager.GetString("Friendship_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больше той любви не бывает, как друг за друга умирает..
        /// </summary>
        public static string Friendship_32 {
            get {
                return ResourceManager.GetString("Friendship_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назвался другом - помогай в беде..
        /// </summary>
        public static string Friendship_33 {
            get {
                return ResourceManager.GetString("Friendship_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to И собака помнит, кто ее кормит..
        /// </summary>
        public static string Friendship_34 {
            get {
                return ResourceManager.GetString("Friendship_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Умный себя винит, глупый - свего товарища..
        /// </summary>
        public static string Friendship_35 {
            get {
                return ResourceManager.GetString("Friendship_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дружба заботой да подмогой крепка..
        /// </summary>
        public static string Friendship_36 {
            get {
                return ResourceManager.GetString("Friendship_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жить не тужить — добро добыть да лиха избыть..
        /// </summary>
        public static string Friendship_37 {
            get {
                return ResourceManager.GetString("Friendship_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Легко друзей найти, да трудно сохранить..
        /// </summary>
        public static string Friendship_38 {
            get {
                return ResourceManager.GetString("Friendship_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Верный друг лучше сотни слуг..
        /// </summary>
        public static string Friendship_39 {
            get {
                return ResourceManager.GetString("Friendship_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бедный знает и друга и недруга..
        /// </summary>
        public static string Friendship_4 {
            get {
                return ResourceManager.GetString("Friendship_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завистливый от чужого счастья сохнет..
        /// </summary>
        public static string Friendship_40 {
            get {
                return ResourceManager.GetString("Friendship_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто друга в беде покидает, тот сам в беду попадает..
        /// </summary>
        public static string Friendship_41 {
            get {
                return ResourceManager.GetString("Friendship_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто вчера солгал, тому и завтра не поверят..
        /// </summary>
        public static string Friendship_42 {
            get {
                return ResourceManager.GetString("Friendship_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Солома с огнем не дружись..
        /// </summary>
        public static string Friendship_43 {
            get {
                return ResourceManager.GetString("Friendship_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Легче друга потерять, чем найти..
        /// </summary>
        public static string Friendship_44 {
            get {
                return ResourceManager.GetString("Friendship_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Столько наговорил, что и в шапку не возьмешь..
        /// </summary>
        public static string Friendship_45 {
            get {
                return ResourceManager.GetString("Friendship_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соха не плуг, приятель не друг..
        /// </summary>
        public static string Friendship_46 {
            get {
                return ResourceManager.GetString("Friendship_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дал слово, держи его..
        /// </summary>
        public static string Friendship_47 {
            get {
                return ResourceManager.GetString("Friendship_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет друга, так ищи, а нашел, так береги..
        /// </summary>
        public static string Friendship_48 {
            get {
                return ResourceManager.GetString("Friendship_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто в нраве крут, тот никому не друг..
        /// </summary>
        public static string Friendship_49 {
            get {
                return ResourceManager.GetString("Friendship_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для милого друга не искать досуга..
        /// </summary>
        public static string Friendship_5 {
            get {
                return ResourceManager.GetString("Friendship_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доброе слово лечит, а злое убивает..
        /// </summary>
        public static string Friendship_50 {
            get {
                return ResourceManager.GetString("Friendship_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сердечный друг не родится вдруг..
        /// </summary>
        public static string Friendship_51 {
            get {
                return ResourceManager.GetString("Friendship_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не будь упрям, а будь прям..
        /// </summary>
        public static string Friendship_52 {
            get {
                return ResourceManager.GetString("Friendship_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как хорош тот, у кого умная голова и доброе сердце..
        /// </summary>
        public static string Friendship_53 {
            get {
                return ResourceManager.GetString("Friendship_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ласковое слово, что вешний сад..
        /// </summary>
        public static string Friendship_54 {
            get {
                return ResourceManager.GetString("Friendship_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друг познается при рати да при беде..
        /// </summary>
        public static string Friendship_55 {
            get {
                return ResourceManager.GetString("Friendship_55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зовется другом, а обирает кругом..
        /// </summary>
        public static string Friendship_56 {
            get {
                return ResourceManager.GetString("Friendship_56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сыр калача белее, а мать всех друзей милее..
        /// </summary>
        public static string Friendship_57 {
            get {
                return ResourceManager.GetString("Friendship_57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На себя не наговаривай, а с друга сговаривай..
        /// </summary>
        public static string Friendship_58 {
            get {
                return ResourceManager.GetString("Friendship_58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не имей 100 рублей а имей 100 друзей!.
        /// </summary>
        public static string Friendship_59 {
            get {
                return ResourceManager.GetString("Friendship_59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не изведан - друг, а изведан - два..
        /// </summary>
        public static string Friendship_6 {
            get {
                return ResourceManager.GetString("Friendship_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для милого дружка и сережку из ушка..
        /// </summary>
        public static string Friendship_60 {
            get {
                return ResourceManager.GetString("Friendship_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добрый конь не без седока, а честный человек не без друга..
        /// </summary>
        public static string Friendship_61 {
            get {
                return ResourceManager.GetString("Friendship_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сабля ранит голову, а слово – душу..
        /// </summary>
        public static string Friendship_62 {
            get {
                return ResourceManager.GetString("Friendship_62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мил да люб, так и будет друг..
        /// </summary>
        public static string Friendship_63 {
            get {
                return ResourceManager.GetString("Friendship_63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to И сват свату друг, да не вдруг..
        /// </summary>
        public static string Friendship_64 {
            get {
                return ResourceManager.GetString("Friendship_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучше ста рублев сто другов..
        /// </summary>
        public static string Friendship_65 {
            get {
                return ResourceManager.GetString("Friendship_65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Знаем вас — были вы у нас: после вас колуна не досчитались..
        /// </summary>
        public static string Friendship_66 {
            get {
                return ResourceManager.GetString("Friendship_66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нашего горя и топоры не секут..
        /// </summary>
        public static string Friendship_67 {
            get {
                return ResourceManager.GetString("Friendship_67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У нашего свата ни друга, ни брата..
        /// </summary>
        public static string Friendship_68 {
            get {
                return ResourceManager.GetString("Friendship_68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чужому горю не смейся..
        /// </summary>
        public static string Friendship_69 {
            get {
                return ResourceManager.GetString("Friendship_69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для друга и семь верст не околица..
        /// </summary>
        public static string Friendship_7 {
            get {
                return ResourceManager.GetString("Friendship_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Иглой да бороной деревня стоит..
        /// </summary>
        public static string Friendship_70 {
            get {
                return ResourceManager.GetString("Friendship_70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вдруг не станешь друг..
        /// </summary>
        public static string Friendship_71 {
            get {
                return ResourceManager.GetString("Friendship_71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гроза, грозись, а мы друг за друга держись..
        /// </summary>
        public static string Friendship_72 {
            get {
                return ResourceManager.GetString("Friendship_72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старый друг лучше новых двух..
        /// </summary>
        public static string Friendship_73 {
            get {
                return ResourceManager.GetString("Friendship_73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ежели несчастья бояться, то и счастья не будет..
        /// </summary>
        public static string Friendship_74 {
            get {
                return ResourceManager.GetString("Friendship_74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друг на друга глядючи, улыбнешься; на себя глядючи только всплачешься..
        /// </summary>
        public static string Friendship_75 {
            get {
                return ResourceManager.GetString("Friendship_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зависть добра не прибавит..
        /// </summary>
        public static string Friendship_76 {
            get {
                return ResourceManager.GetString("Friendship_76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жить было с другом, да помешал недруг..
        /// </summary>
        public static string Friendship_77 {
            get {
                return ResourceManager.GetString("Friendship_77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто ищет, тот найдет..
        /// </summary>
        public static string Friendship_78 {
            get {
                return ResourceManager.GetString("Friendship_78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С волками жить - по волчьи выть..
        /// </summary>
        public static string Friendship_79 {
            get {
                return ResourceManager.GetString("Friendship_79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друзей много, а друга нет..
        /// </summary>
        public static string Friendship_8 {
            get {
                return ResourceManager.GetString("Friendship_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет такого дружка, как родная матушка..
        /// </summary>
        public static string Friendship_80 {
            get {
                return ResourceManager.GetString("Friendship_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дальний путь, да ближний друг..
        /// </summary>
        public static string Friendship_81 {
            get {
                return ResourceManager.GetString("Friendship_81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все за одного и один за всех..
        /// </summary>
        public static string Friendship_82 {
            get {
                return ResourceManager.GetString("Friendship_82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все любят добро, да не всех любит оно..
        /// </summary>
        public static string Friendship_83 {
            get {
                return ResourceManager.GetString("Friendship_83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По щедрости руки видно, какое сердце..
        /// </summary>
        public static string Friendship_84 {
            get {
                return ResourceManager.GetString("Friendship_84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доброе братство дороже богатства..
        /// </summary>
        public static string Friendship_85 {
            get {
                return ResourceManager.GetString("Friendship_85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нужно много дней и ночей, чтобы узнать человека..
        /// </summary>
        public static string Friendship_86 {
            get {
                return ResourceManager.GetString("Friendship_86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одежда лучше новая, а друг - старый..
        /// </summary>
        public static string Friendship_87 {
            get {
                return ResourceManager.GetString("Friendship_87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дружба дружбой, а служба службой..
        /// </summary>
        public static string Friendship_88 {
            get {
                return ResourceManager.GetString("Friendship_88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Царю правда лучший друг..
        /// </summary>
        public static string Friendship_89 {
            get {
                return ResourceManager.GetString("Friendship_89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От теплого слова и лед тает..
        /// </summary>
        public static string Friendship_9 {
            get {
                return ResourceManager.GetString("Friendship_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучше вода у друга, чем мед у врага..
        /// </summary>
        public static string Friendship_90 {
            get {
                return ResourceManager.GetString("Friendship_90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Берись дружно, не будет грузно..
        /// </summary>
        public static string Friendship_91 {
            get {
                return ResourceManager.GetString("Friendship_91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В недруге стрела, что во пне, а в друге, что во мне..
        /// </summary>
        public static string Friendship_92 {
            get {
                return ResourceManager.GetString("Friendship_92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Два горя вместе, третье пополам..
        /// </summary>
        public static string Friendship_93 {
            get {
                return ResourceManager.GetString("Friendship_93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дорог не подарок, дорога любовь..
        /// </summary>
        public static string Friendship_94 {
            get {
                return ResourceManager.GetString("Friendship_94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друг неиспытанный, что орех нерасколотый..
        /// </summary>
        public static string Friendship_95 {
            get {
                return ResourceManager.GetString("Friendship_95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друга на деньги не купишь..
        /// </summary>
        public static string Friendship_96 {
            get {
                return ResourceManager.GetString("Friendship_96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дружба крепка не лестью, а правдой и честью..
        /// </summary>
        public static string Friendship_97 {
            get {
                return ResourceManager.GetString("Friendship_97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дружба от недружбы близко живет..
        /// </summary>
        public static string Friendship_98 {
            get {
                return ResourceManager.GetString("Friendship_98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to И комар лошадь свалит, коли волк подсобит..
        /// </summary>
        public static string Friendship_99 {
            get {
                return ResourceManager.GetString("Friendship_99", resourceCulture);
            }
        }
    }
}
