//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarumaResourcesPortable.LocalizationResources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Health {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Health() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DarumaResourcesPortable.LocalizationResources.Health", typeof(Health).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Болен - лечись, а здоров - берегись..
        /// </summary>
        public static string Health_0 {
            get {
                return ResourceManager.GetString("Health_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каждому своя болезнь тяжела..
        /// </summary>
        public static string Health_1 {
            get {
                return ResourceManager.GetString("Health_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Людям скромно, а нам на здоровье..
        /// </summary>
        public static string Health_10 {
            get {
                return ResourceManager.GetString("Health_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to После обеда полежи, после ужина походи..
        /// </summary>
        public static string Health_11 {
            get {
                return ResourceManager.GetString("Health_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хотя не скоро, да здорово..
        /// </summary>
        public static string Health_12 {
            get {
                return ResourceManager.GetString("Health_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не всякая болезнь к смерти..
        /// </summary>
        public static string Health_13 {
            get {
                return ResourceManager.GetString("Health_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больны раны на своих плечах..
        /// </summary>
        public static string Health_14 {
            get {
                return ResourceManager.GetString("Health_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больному и золотая кровать не поможет..
        /// </summary>
        public static string Health_15 {
            get {
                return ResourceManager.GetString("Health_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доброму человеку и чужая болезнь к сердцу..
        /// </summary>
        public static string Health_16 {
            get {
                return ResourceManager.GetString("Health_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всякая болезнь идет к сердцу..
        /// </summary>
        public static string Health_17 {
            get {
                return ResourceManager.GetString("Health_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Когда-то черт умрет, а он еще и не хворает..
        /// </summary>
        public static string Health_18 {
            get {
                return ResourceManager.GetString("Health_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В добром здоровье и хворать хорошо..
        /// </summary>
        public static string Health_19 {
            get {
                return ResourceManager.GetString("Health_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Боль без языка, да сказывается..
        /// </summary>
        public static string Health_2 {
            get {
                return ResourceManager.GetString("Health_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Замерзших - больше чем зажаренных..
        /// </summary>
        public static string Health_20 {
            get {
                return ResourceManager.GetString("Health_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Руби дерево здоровое, а гнилое и само свалится..
        /// </summary>
        public static string Health_21 {
            get {
                return ResourceManager.GetString("Health_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я глупый, но здоровый..
        /// </summary>
        public static string Health_22 {
            get {
                return ResourceManager.GetString("Health_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вовремя старость, не к делу хворь..
        /// </summary>
        public static string Health_23 {
            get {
                return ResourceManager.GetString("Health_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если хочешь быть здоров - закаляйся..
        /// </summary>
        public static string Health_24 {
            get {
                return ResourceManager.GetString("Health_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что скоро, то хворо..
        /// </summary>
        public static string Health_25 {
            get {
                return ResourceManager.GetString("Health_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жди, когда черт умрет: он и хворать не думал..
        /// </summary>
        public static string Health_26 {
            get {
                return ResourceManager.GetString("Health_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Застарелую болезнь трудно лечить..
        /// </summary>
        public static string Health_27 {
            get {
                return ResourceManager.GetString("Health_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хлеб да крупы на здоровье лупи..
        /// </summary>
        public static string Health_28 {
            get {
                return ResourceManager.GetString("Health_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Болячка мала, да болезнь велика..
        /// </summary>
        public static string Health_29 {
            get {
                return ResourceManager.GetString("Health_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Береги платье снову, а здоровье смолоду..
        /// </summary>
        public static string Health_3 {
            get {
                return ResourceManager.GetString("Health_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Болит бок девятый год, не знаю которо место..
        /// </summary>
        public static string Health_30 {
            get {
                return ResourceManager.GetString("Health_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шуба елова, да к сердцу здорова..
        /// </summary>
        public static string Health_31 {
            get {
                return ResourceManager.GetString("Health_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Болен - через силу хворает..
        /// </summary>
        public static string Health_32 {
            get {
                return ResourceManager.GetString("Health_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Румянами хворь не лечат..
        /// </summary>
        public static string Health_33 {
            get {
                return ResourceManager.GetString("Health_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дурака учить - что горбатого лечить..
        /// </summary>
        public static string Health_34 {
            get {
                return ResourceManager.GetString("Health_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ты мне не здорово, а я тебе не челом..
        /// </summary>
        public static string Health_35 {
            get {
                return ResourceManager.GetString("Health_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто в двадцать лет не здоров, в тридцать не умен, а в сорок не богат, тому век таким не бывать..
        /// </summary>
        public static string Health_36 {
            get {
                return ResourceManager.GetString("Health_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больна жена мужу не мила..
        /// </summary>
        public static string Health_37 {
            get {
                return ResourceManager.GetString("Health_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без случайности человеку век не прожить..
        /// </summary>
        public static string Health_38 {
            get {
                return ResourceManager.GetString("Health_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Где кашель, там и хворь..
        /// </summary>
        public static string Health_39 {
            get {
                return ResourceManager.GetString("Health_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приехал - не здоровался, поехал - не простился..
        /// </summary>
        public static string Health_4 {
            get {
                return ResourceManager.GetString("Health_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не бойся дороги, были б кони здоровы..
        /// </summary>
        public static string Health_40 {
            get {
                return ResourceManager.GetString("Health_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучше сорок раз - вспотеть, чем один - заиндеветь..
        /// </summary>
        public static string Health_41 {
            get {
                return ResourceManager.GetString("Health_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больному и мед не вкусен, а здоровый и камень ест..
        /// </summary>
        public static string Health_42 {
            get {
                return ResourceManager.GetString("Health_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больной от могилы бежит, а здоровый в могилу спешит..
        /// </summary>
        public static string Health_43 {
            get {
                return ResourceManager.GetString("Health_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Болезнь и поросенка не красит..
        /// </summary>
        public static string Health_44 {
            get {
                return ResourceManager.GetString("Health_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Любовь до гроба - дураки оба..
        /// </summary>
        public static string Health_45 {
            get {
                return ResourceManager.GetString("Health_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дай бог здоровья кнуту да хомуту, а лошадь довезет..
        /// </summary>
        public static string Health_46 {
            get {
                return ResourceManager.GetString("Health_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь не красен, да здоров..
        /// </summary>
        public static string Health_47 {
            get {
                return ResourceManager.GetString("Health_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С больной головы да на здоровую..
        /// </summary>
        public static string Health_48 {
            get {
                return ResourceManager.GetString("Health_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нищий болезней ищет, а к богатому они сами идут..
        /// </summary>
        public static string Health_49 {
            get {
                return ResourceManager.GetString("Health_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Болезнь да горе изведут скоро..
        /// </summary>
        public static string Health_5 {
            get {
                return ResourceManager.GetString("Health_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тебе на здоровье, да и нам нескромно..
        /// </summary>
        public static string Health_50 {
            get {
                return ResourceManager.GetString("Health_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Муж любит жену здоровую, а брат сестру богатую..
        /// </summary>
        public static string Health_51 {
            get {
                return ResourceManager.GetString("Health_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто не болел, тот здоровью цены не знает..
        /// </summary>
        public static string Health_52 {
            get {
                return ResourceManager.GetString("Health_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Баня здоровит, разговор веселит..
        /// </summary>
        public static string Health_53 {
            get {
                return ResourceManager.GetString("Health_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хотя бы изба елова, да сердце здорово..
        /// </summary>
        public static string Health_54 {
            get {
                return ResourceManager.GetString("Health_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто встал до дня, тот днем здоров..
        /// </summary>
        public static string Health_55 {
            get {
                return ResourceManager.GetString("Health_55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кожа-то елова, да сердце-то здорово..
        /// </summary>
        public static string Health_56 {
            get {
                return ResourceManager.GetString("Health_56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Где здоровье, там и красота..
        /// </summary>
        public static string Health_57 {
            get {
                return ResourceManager.GetString("Health_57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грамота не болезнь - годы не уносит..
        /// </summary>
        public static string Health_58 {
            get {
                return ResourceManager.GetString("Health_58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От здоровья не лечатся.
        /// </summary>
        public static string Health_59 {
            get {
                return ResourceManager.GetString("Health_59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрытую рану лечить трудно..
        /// </summary>
        public static string Health_6 {
            get {
                return ResourceManager.GetString("Health_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У кого пропало, у того б в горле торчало, а кто украл, тому бы на здоровье..
        /// </summary>
        public static string Health_60 {
            get {
                return ResourceManager.GetString("Health_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По здоровом сынке сердце ноет, по больном вдвое..
        /// </summary>
        public static string Health_61 {
            get {
                return ResourceManager.GetString("Health_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Человека лень не кормит, а здоровье только портит..
        /// </summary>
        public static string Health_62 {
            get {
                return ResourceManager.GetString("Health_62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не дай бог лечиться да судиться..
        /// </summary>
        public static string Health_63 {
            get {
                return ResourceManager.GetString("Health_63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лук семь недугов лечит, а чеснок семь недугов изводит..
        /// </summary>
        public static string Health_64 {
            get {
                return ResourceManager.GetString("Health_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Болезнь нас не спрашивает..
        /// </summary>
        public static string Health_65 {
            get {
                return ResourceManager.GetString("Health_65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Других лечить беремся, а сами больны..
        /// </summary>
        public static string Health_66 {
            get {
                return ResourceManager.GetString("Health_66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to И одна корова, да есть здорова..
        /// </summary>
        public static string Health_67 {
            get {
                return ResourceManager.GetString("Health_67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дал бог здоровья, да денег нет..
        /// </summary>
        public static string Health_68 {
            get {
                return ResourceManager.GetString("Health_68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что русскому здорово, то немцу смерть..
        /// </summary>
        public static string Health_69 {
            get {
                return ResourceManager.GetString("Health_69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чистота - половина здоровья..
        /// </summary>
        public static string Health_7 {
            get {
                return ResourceManager.GetString("Health_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сердобольный врач ухудшает страдания..
        /// </summary>
        public static string Health_70 {
            get {
                return ResourceManager.GetString("Health_70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дай боли волю, она в дугу согнет..
        /// </summary>
        public static string Health_71 {
            get {
                return ResourceManager.GetString("Health_71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На всякую болезнь зелье вырастает..
        /// </summary>
        public static string Health_72 {
            get {
                return ResourceManager.GetString("Health_72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нога споткнется, а голове достанется..
        /// </summary>
        public static string Health_73 {
            get {
                return ResourceManager.GetString("Health_73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рана, нанесенная самому себе, плохо заживает..
        /// </summary>
        public static string Health_74 {
            get {
                return ResourceManager.GetString("Health_74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больное место скорее ушибешь..
        /// </summary>
        public static string Health_75 {
            get {
                return ResourceManager.GetString("Health_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не каждый больной, кто стонет..
        /// </summary>
        public static string Health_76 {
            get {
                return ResourceManager.GetString("Health_76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бабий век - сорок лет..
        /// </summary>
        public static string Health_8 {
            get {
                return ResourceManager.GetString("Health_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потерявши голову по волосам не плачут..
        /// </summary>
        public static string Health_9 {
            get {
                return ResourceManager.GetString("Health_9", resourceCulture);
            }
        }
    }
}
