//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarumaResourcesPortable.LocalizationResources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Health2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Health2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DarumaResourcesPortable.LocalizationResources.Health2", typeof(Health2).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Побороть дурные привычки проще сегодня, чем завтра.
        ///Конфуций.
        /// </summary>
        internal static string Health2_0 {
            get {
                return ResourceManager.GetString("Health2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — Боль — это дар? 
        ///— Конечно. Она делает нас глубже и знакомит нас с теми, кем мы на самом деле являемся. Древние мудрецы считали, что те, кто больше всех страдает, благословлены Богом..
        /// </summary>
        internal static string Health2_1 {
            get {
                return ResourceManager.GetString("Health2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самое лучшее лекарство не поможет больному, если он отказывается его принять. 
        ///МИГЕЛЬ ДЕ СЕРВАНТЕС.
        /// </summary>
        internal static string Health2_10 {
            get {
                return ResourceManager.GetString("Health2_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Человек не должен утрачивать желания. Это мощные стимулы к творчеству, любви и долголетию.
        ///А.А.Богомолец.
        /// </summary>
        internal static string Health2_100 {
            get {
                return ResourceManager.GetString("Health2_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только здоровый человек может быть свободным, радостным, счастливым. И наоборот – свободный, радостный и счастливый вскоре обретет здоровье..
        /// </summary>
        internal static string Health2_101 {
            get {
                return ResourceManager.GetString("Health2_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здоровье гораздо более зависит от наших привычек и питания, чем от врачебного искусства.
        ///Джон Леббок.
        /// </summary>
        internal static string Health2_102 {
            get {
                return ResourceManager.GetString("Health2_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Умеренность есть как бы мать хорошего здоровья.
        ///Максим Валерий.
        /// </summary>
        internal static string Health2_103 {
            get {
                return ResourceManager.GetString("Health2_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если на сердце скребут кошки значит, нужна валерьянка.
        ///Николай Барановский.
        /// </summary>
        internal static string Health2_104 {
            get {
                return ResourceManager.GetString("Health2_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Человек — высший продукт земной природы. Но для того, чтобы наслаждаться сокровищами природы, человек должен быть здоровым, сильным и умным.
        ///Павлов И. П..
        /// </summary>
        internal static string Health2_105 {
            get {
                return ResourceManager.GetString("Health2_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Безумие — это многократное повторение одного и того же действия с ожиданием разных результатов.
        ///Альберт Эйнштейн.
        /// </summary>
        internal static string Health2_106 {
            get {
                return ResourceManager.GetString("Health2_106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здоровье человека не в сердце, не в почках, не в корнях, не в листве или спине. Конечно, слов нет, хорошо человеку, если у него все это тоже здорово, как у быков. Но самая суть чисто человеческого здоровья — это когда его неудержимо тянет сказать что-то хорошее другому человеку, как будто это даже закон: раз мне — то должно быть и всем хорошо!
        ///М.М. Пришвин.
        /// </summary>
        internal static string Health2_107 {
            get {
                return ResourceManager.GetString("Health2_107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Праздность и ничегонеделание влекут за собой порочность и нездоровье - напротив того, устремление ума к чему-либо приносит за собой бодрость, вечно направленную к укреплению жизни.
        ///Гипократ.
        /// </summary>
        internal static string Health2_108 {
            get {
                return ResourceManager.GetString("Health2_108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пища столь же необходима для здоровья, сколь необходимо приличное обращение человеку образованному.
        ///Козьма Прутков.
        /// </summary>
        internal static string Health2_109 {
            get {
                return ResourceManager.GetString("Health2_109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здоровье не купишь, зато расплачиваться им можно сколько угодно..
        /// </summary>
        internal static string Health2_11 {
            get {
                return ResourceManager.GetString("Health2_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Никакое тело не может быть столь крепким, чтобы вино не могло повредить его.
        ///Плутарх.
        /// </summary>
        internal static string Health2_110 {
            get {
                return ResourceManager.GetString("Health2_110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to И мама, и Минздрав предупреждали…
        ///Четвёртова Майя.
        /// </summary>
        internal static string Health2_111 {
            get {
                return ResourceManager.GetString("Health2_111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто здоров, тот и молод.
        ///Г.Бон.
        /// </summary>
        internal static string Health2_112 {
            get {
                return ResourceManager.GetString("Health2_112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Когда семидесятилетнего Бернарда Шоу спросили о его самочувствии, то он ответил: «Прекрасно, прекрасно, только мне докучают врачи, утверждая, что я умру, потому что не ем мяса». Когда же к девяностолетнему Шоу обратились с тем же вопросом, он отвечал: «Прекрасно. Больше меня никто не беспокоит. Все врачи, которые мучили меня, утверждая, что я не смогу прожить без мяса, уже умерли».
        ///Бернард Шоу.
        /// </summary>
        internal static string Health2_113 {
            get {
                return ResourceManager.GetString("Health2_113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здоровье до того перевешивает все остальные блага жизни, что поистине здоровый нищий счастливее больного короля.
        ///Шопенгауэр А..
        /// </summary>
        internal static string Health2_114 {
            get {
                return ResourceManager.GetString("Health2_114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я верю в бога, только для меня – это Природа.
        ///Франк Ллойд Райт.
        /// </summary>
        internal static string Health2_115 {
            get {
                return ResourceManager.GetString("Health2_115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех обычно не приходит в результате одного усилия, это скорее сумма многих усилий.
        ///Адам Джексон — 10 секретов богатства..
        /// </summary>
        internal static string Health2_116 {
            get {
                return ResourceManager.GetString("Health2_116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Короткую жизнь мы не получаем, а делаем ее такою; не бедны мы жизнью, а пользуемся ею расточительно. Жизнь длинна, если ею умело пользоваться.
        ///Сенека.
        /// </summary>
        internal static string Health2_117 {
            get {
                return ResourceManager.GetString("Health2_117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прежде чем лечь на операцию, приведи в порядок свои земные дела. Возможно, ты еще выживешь.
        ///Амброз Бирс.
        /// </summary>
        internal static string Health2_118 {
            get {
                return ResourceManager.GetString("Health2_118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Излишняя забота — такое же проклятье стариков, как беззаботность – горе молодежи.
        ///У. Шекспир.
        /// </summary>
        internal static string Health2_119 {
            get {
                return ResourceManager.GetString("Health2_119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здоровье – это когда у вас каждый день болит в другом месте..
        /// </summary>
        internal static string Health2_12 {
            get {
                return ResourceManager.GetString("Health2_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если бы мне пришлось заботиться о проблемах пользователей, забытых паролях или бэкапах, я бы не знал что и делать. Наверное, стал бы наркоманом и алкоголиком, чтобы притупить боль.
        ///Линус Торвальдс.
        /// </summary>
        internal static string Health2_120 {
            get {
                return ResourceManager.GetString("Health2_120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гигиена и медицина тоже важны, но важнее всего здоровье.
        ///Хьюго Штейнхаус.
        /// </summary>
        internal static string Health2_121 {
            get {
                return ResourceManager.GetString("Health2_121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тот, кто хочет видеть результаты своего труда немедленно, должен идти в сапожники.
        ///Альберт Эйнштейн.
        /// </summary>
        internal static string Health2_122 {
            get {
                return ResourceManager.GetString("Health2_122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здоровье — дороже золота.
        ///Шекспир У..
        /// </summary>
        internal static string Health2_123 {
            get {
                return ResourceManager.GetString("Health2_123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здоровье до того перевешивает все остальные блага жизни, что поистине здоровый нищий счастливее больного короля.
        ///Шопенгауэр А..
        /// </summary>
        internal static string Health2_124 {
            get {
                return ResourceManager.GetString("Health2_124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здоровье человека не в сердце, не в почках, не в корнях, не в листве или спине. Конечно, слов нет, хорошо человеку, если у него все это тоже здорово, как у быков. Но самая суть чисто человеческого здоровья — это когда его неудержимо тянет сказать что-то хорошее другому человеку, как будто это даже закон: раз мне — то должно быть и всем хорошо!
        ///Пришвин М. М..
        /// </summary>
        internal static string Health2_125 {
            get {
                return ResourceManager.GetString("Health2_125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Из всех лекарств лучшее — отдых и воздержание.
        ///Франклин Б..
        /// </summary>
        internal static string Health2_126 {
            get {
                return ResourceManager.GetString("Health2_126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Надо непременно встряхивать себя физически, чтобы быть здоровым нравственно.
        ///Толстой Л. Н..
        /// </summary>
        internal static string Health2_127 {
            get {
                return ResourceManager.GetString("Health2_127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не всегда во власти врача исцелить больного.
        ///Овидий.
        /// </summary>
        internal static string Health2_128 {
            get {
                return ResourceManager.GetString("Health2_128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет искусства полезнее медицины.
        ///Плиний.
        /// </summary>
        internal static string Health2_129 {
            get {
                return ResourceManager.GetString("Health2_129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Болезнь – это состояние организма, когда не хочется даже того, что запретил доктор..
        /// </summary>
        internal static string Health2_13 {
            get {
                return ResourceManager.GetString("Health2_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто крепок телом, может терпеть и жару, и холод. Так и тот, кто здоров душевно, в состоянии перенести и гнев, и горе, и радость, и остальные чувства.
        ///Эпиктет.
        /// </summary>
        internal static string Health2_130 {
            get {
                return ResourceManager.GetString("Health2_130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если не бегаешь, пока здоров, придется побегать, когда заболеешь.
        ///Гораций.
        /// </summary>
        internal static string Health2_131 {
            get {
                return ResourceManager.GetString("Health2_131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одни вечно больны только потому, что очень заботятся быть здоровыми, а другие здоровы только потому, что не боятся быть больными.
        ///Ключевский В..
        /// </summary>
        internal static string Health2_132 {
            get {
                return ResourceManager.GetString("Health2_132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Философия и медицина сделали человека самым разумным из животных, гадание и астрология — самым безумным, суеверие и деспотизм — самым несчастным.
        ///Диоген.
        /// </summary>
        internal static string Health2_133 {
            get {
                return ResourceManager.GetString("Health2_133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все мы, когда здоровы, легко даем хорошие советы больным.
        ///Теренций.
        /// </summary>
        internal static string Health2_134 {
            get {
                return ResourceManager.GetString("Health2_134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высшее благо достигается на основе полного физического и умственного здоровья.
        ///Цицерон.
        /// </summary>
        internal static string Health2_135 {
            get {
                return ResourceManager.GetString("Health2_135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Противодействуй болезни вначале; поздно думать о лекарствах, когда болезнь укоренилась от долгого промедления.
        ///Овидий.
        /// </summary>
        internal static string Health2_136 {
            get {
                return ResourceManager.GetString("Health2_136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одно из условий выздоровления — желание выздороветь.
        ///Сенека.
        /// </summary>
        internal static string Health2_137 {
            get {
                return ResourceManager.GetString("Health2_137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если заниматься физическими упражнениями — нет никакой нужды в употреблении лекарств, принимаемых при разных болезнях, если в то же время соблюдать все прочие предписания нормального режима.
        ///Ибн Сина.
        /// </summary>
        internal static string Health2_138 {
            get {
                return ResourceManager.GetString("Health2_138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ничто так не обязательно всему роду человеческому, как медицина.
        ///Квинтилиан.
        /// </summary>
        internal static string Health2_139 {
            get {
                return ResourceManager.GetString("Health2_139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский человек болезненнее всего переносит здоровый образ жизни..
        /// </summary>
        internal static string Health2_14 {
            get {
                return ResourceManager.GetString("Health2_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет на свете прекраснее одёжи,
        ///Чем бронза мускулов и свежесть кожи.
        ///Маяковский В. В..
        /// </summary>
        internal static string Health2_140 {
            get {
                return ResourceManager.GetString("Health2_140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здоровье так же заразительно, как и болезнь.
        ///Роллан Р..
        /// </summary>
        internal static string Health2_141 {
            get {
                return ResourceManager.GetString("Health2_141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пока у больного есть дыхание, говорят, есть и надежда.
        ///Цицерон.
        /// </summary>
        internal static string Health2_142 {
            get {
                return ResourceManager.GetString("Health2_142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если у тебя все в порядке с желудком, грудью, ногами, никакие царские сокровища не смогут ничего прибавить.
        ///Гораций.
        /// </summary>
        internal static string Health2_143 {
            get {
                return ResourceManager.GetString("Health2_143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ничто так не препятствует здоровью, как частая смена лекарств.
        ///Сенека.
        /// </summary>
        internal static string Health2_144 {
            get {
                return ResourceManager.GetString("Health2_144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если человек сам следит за своим здоровьем, то трудно найти врача, который знал бы лучше полезное для его здоровья, чем он сам.
        ///Сократ.
        /// </summary>
        internal static string Health2_145 {
            get {
                return ResourceManager.GetString("Health2_145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Врач — философ: ведь нет большой разницы между мудростью и медициной.
        ///Гиппократ.
        /// </summary>
        internal static string Health2_146 {
            get {
                return ResourceManager.GetString("Health2_146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для соразмерности, красоты и здоровья требуется не только образование в области наук и искусства, но и занятия всю жизнь физическими упражнениями, гимнастикой.
        ///Платон.
        /// </summary>
        internal static string Health2_147 {
            get {
                return ResourceManager.GetString("Health2_147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто рассчитывает обеспечить себе здоровье, пребывая в лени, тот поступает так же глупо, как и человек, думающий молчанием усовершенствовать свой голос.
        ///Плутарх.
        /// </summary>
        internal static string Health2_148 {
            get {
                return ResourceManager.GetString("Health2_148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Медицина — одно из величайших заблуждений человечества.
        ///Мольер.
        /// </summary>
        internal static string Health2_149 {
            get {
                return ResourceManager.GetString("Health2_149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я болел три дня, и это прекрасно отразилось на моём здоровье.
        ///СЕРГЕЙ ДОВЛАТОВ.
        /// </summary>
        internal static string Health2_15 {
            get {
                return ResourceManager.GetString("Health2_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всеисцеляющего средства не существует.
        ///Бомарше П..
        /// </summary>
        internal static string Health2_150 {
            get {
                return ResourceManager.GetString("Health2_150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добросовестный врач, прежде чем назначить больному лечение, должен узнать не только его болезнь, но и привычки его в здоровом состоянии, и свойства тела.
        ///Цицерон.
        /// </summary>
        internal static string Health2_151 {
            get {
                return ResourceManager.GetString("Health2_151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тот, кто хочет быть здоровым, отчасти уже выздоравливает.
        ///Боккаччо Д..
        /// </summary>
        internal static string Health2_152 {
            get {
                return ResourceManager.GetString("Health2_152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Девять десятых нашего счастья зависит от здоровья.
        ///Шопенгауэр А..
        /// </summary>
        internal static string Health2_153 {
            get {
                return ResourceManager.GetString("Health2_153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Великое преимущество врача заключается в том, что он не обязан следовать собственным советам.
        ///Кристи А..
        /// </summary>
        internal static string Health2_154 {
            get {
                return ResourceManager.GetString("Health2_154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гимнастика, физические упражнения, ходьба должны прочно войти в повседневный быт каждого, кто хочет сохранить работоспособность, здоровье, полноценную и радостную жизнь.
        ///Гиппократ.
        /// </summary>
        internal static string Health2_155 {
            get {
                return ResourceManager.GetString("Health2_155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучший врач тот, кто знает бесполезность большинства лекарств.
        ///Франклин Б..
        /// </summary>
        internal static string Health2_156 {
            get {
                return ResourceManager.GetString("Health2_156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Человек любит поговорить о своих болезнях, а между тем это самое неинтересное в его жизни.
        ///Чехов А. П..
        /// </summary>
        internal static string Health2_157 {
            get {
                return ResourceManager.GetString("Health2_157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия диетических средств продолжительны, а действия лекарств — скоропреходящи.
        ///Гиппократ.
        /// </summary>
        internal static string Health2_158 {
            get {
                return ResourceManager.GetString("Health2_158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здоровье есть само удовольствие или неизбежно порождает удовольствие, как огонь создает теплоту.
        ///Томас Мор.
        /// </summary>
        internal static string Health2_159 {
            get {
                return ResourceManager.GetString("Health2_159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Владыки древнего востока платили своим врачам только тогда, когда были здоровы..
        /// </summary>
        internal static string Health2_16 {
            get {
                return ResourceManager.GetString("Health2_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жизнь коротка, путь искусства долог, удобный случай скоропреходящ, опыт обманчив, суждение трудно. Поэтому не только сам врач должен употреблять в дело все, что необходимо, но и больной, и окружающие, и все внешние обстоятельства должны способствовать врачу в его деятельности.
        ///Гиппократ.
        /// </summary>
        internal static string Health2_160 {
            get {
                return ResourceManager.GetString("Health2_160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чувство выздоровления — одно из самых сладостных.
        ///Пушкин А. С..
        /// </summary>
        internal static string Health2_161 {
            get {
                return ResourceManager.GetString("Health2_161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Воздержанность и труд — вот два истинных врача человека: труд обостряет его аппетит, а воздержанность мешает злоупотреблять им.
        ///Руссо Ж..
        /// </summary>
        internal static string Health2_162 {
            get {
                return ResourceManager.GetString("Health2_162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Судите о своем здоровье по тому, как вы радуетесь утру и весне.
        ///Торо Г..
        /// </summary>
        internal static string Health2_163 {
            get {
                return ResourceManager.GetString("Health2_163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гимнастика есть целительная часть медицины.
        ///Платон.
        /// </summary>
        internal static string Health2_164 {
            get {
                return ResourceManager.GetString("Health2_164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нужно поддерживать крепость тела, чтобы сохранить крепость духа.
        ///Гюго В..
        /// </summary>
        internal static string Health2_165 {
            get {
                return ResourceManager.GetString("Health2_165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наши пищевые вещества должны быть лечебным средством, а наши лечебные средства должны быть пищевыми веществами.
        ///Гиппократ.
        /// </summary>
        internal static string Health2_166 {
            get {
                return ResourceManager.GetString("Health2_166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У женщины — как опыт учит нас — Здоровье с красотою неразлучны.
        ///Лопе де Вега.
        /// </summary>
        internal static string Health2_167 {
            get {
                return ResourceManager.GetString("Health2_167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Болезнь — это крест, но, может, и опора. Идеально было бы взять у нее силу и отвергнуть слабости. Пусть она станет убежищем, которое придает силу в нужный момент. А если платить нужно страданиями и отречением — заплатим.
        ///Камю А..
        /// </summary>
        internal static string Health2_168 {
            get {
                return ResourceManager.GetString("Health2_168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не навреди (больному).
        ///Гиппократ.
        /// </summary>
        internal static string Health2_169 {
            get {
                return ResourceManager.GetString("Health2_169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Болезни – рекламные агенты смерти.
        ///ДЖЕЙМС ДЖОЙС, «Улисс».
        /// </summary>
        internal static string Health2_17 {
            get {
                return ResourceManager.GetString("Health2_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Большая часть болезней наших — это дело наших собственных рук.
        ///Руссо Ж. Ж.
        /// </summary>
        internal static string Health2_170 {
            get {
                return ResourceManager.GetString("Health2_170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ни насыщение, ни голод и ничто другое не хорошо, если преступить меру природы.
        ///Гиппократ.
        /// </summary>
        internal static string Health2_171 {
            get {
                return ResourceManager.GetString("Health2_171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гимнастика удлиняет молодость человека.
        ///Джон Локк.
        /// </summary>
        internal static string Health2_172 {
            get {
                return ResourceManager.GetString("Health2_172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Праздность и ничегонеделание влекут за собой порочность и нездоровье — напротив того, устремление ума к чему-либо приносит за собой бодрость, вечно направленную к укреплению жизни.
        ///Гиппократ.
        /// </summary>
        internal static string Health2_173 {
            get {
                return ResourceManager.GetString("Health2_173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если будешь следовать природе, то навсегда останешься здоровым.
        ///Пенн Вильям.
        /// </summary>
        internal static string Health2_174 {
            get {
                return ResourceManager.GetString("Health2_174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наиболее деятельным союзником болезни является уныние больного.
        ///Горький М..
        /// </summary>
        internal static string Health2_175 {
            get {
                return ResourceManager.GetString("Health2_175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Противоположное излечивается противоположным.
        ///Гиппократ.
        /// </summary>
        internal static string Health2_176 {
            get {
                return ResourceManager.GetString("Health2_176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я хочу при помощи гимнастики всего тела сделать его более уравновешенным.
        ///Сократ.
        /// </summary>
        internal static string Health2_177 {
            get {
                return ResourceManager.GetString("Health2_177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здоровый дух в здоровом теле — вот краткое, но полное описание счастливого состояния в этом мире.
        ///Джон Локк.
        /// </summary>
        internal static string Health2_178 {
            get {
                return ResourceManager.GetString("Health2_178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как суконщики чистят сукна, выбивая их от пыли, так гимнастика очищает организм.
        ///Свифт Д..
        /// </summary>
        internal static string Health2_179 {
            get {
                return ResourceManager.GetString("Health2_179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Врач любит своих безнадёжных, с того света вытащенных больных не меньше, чем они его.
        ///Исаак Гантман, герой книги ЛЮДМИЛЫ УЛИЦКОЙ «Даниэль Штайн, переводчик».
        /// </summary>
        internal static string Health2_18 {
            get {
                return ResourceManager.GetString("Health2_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Надежда выздороветь — половица выздоровления.
        ///Вольтер.
        /// </summary>
        internal static string Health2_180 {
            get {
                return ResourceManager.GetString("Health2_180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лечит болезни врач, но излечивает природа.
        ///Гиппократ.
        /// </summary>
        internal static string Health2_181 {
            get {
                return ResourceManager.GetString("Health2_181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как нельзя приступить к лечению глаза, не думая о голове, или лечить голову, не думая о всем организме, так нельзя лечить тело, не леча душу.
        ///Сократ.
        /// </summary>
        internal static string Health2_182 {
            get {
                return ResourceManager.GetString("Health2_182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следуйте вечным трем правилам:
        ///Уважай себя
        ///Уважай других
        ///Не уходи от ответственности за свои действия.
        ///Далай Лама.
        /// </summary>
        internal static string Health2_183 {
            get {
                return ResourceManager.GetString("Health2_183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С первого момента появления на свет мы оказываемся под крылом опеки и доброты наших родителей.
        ///Затем на склоне лет, когда к нам подступают болезни и старость, мы вновь отдаем себя на милость других.
        ///Если в начале и конце нашей жизни мы так полагаемся на милость других существ, как же может случиться, что посередине мы отказываем им в доброте?»
        ///Далай Лама.
        /// </summary>
        internal static string Health2_184 {
            get {
                return ResourceManager.GetString("Health2_184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наши дома всё больше, а семьи всё меньше.
        ///У нас больше удобств, но меньше времени.
        ///Больше ученых степеней, но меньше здравого смысла.
        ///Больше знаний, но меньше способности к трезвому суждению.
        ///Больше специалистов, но еще больше проблем.
        ///Больше лекарств, но меньше здоровья.
        ///Мы проделали долгий путь до Луны и обратно,
        ///Но нам сложно перейти батик улицу, чтобы встретиться с новым соседом.
        ///Мы создали множество компьютеров для хранения и копирования
        ///огромных объемов информации, но стали меньше общаться др [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Health2_185 {
            get {
                return ResourceManager.GetString("Health2_185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что бы не произошло – никогда не сдавайся!
        ///Развивай своё сердце.
        ///Слишком много энергии в вашей стране
        ///Тратится на развитие ума, а не сердца.
        ///Развивай своё сердце, будь сострадательным
        ///Не только к своим друзьям, но к каждому.
        ///Будь сострадательным, трудись ради мира в своём сердце и во всём мире.
        ///Работай во имя мира, и я повторю снова: никогда не сдавайся.
        ///Не важно, что происходит вокруг тебя, не важно, что произошло с тобой – никогда не сдавайся!
        ///Далай Лама.
        /// </summary>
        internal static string Health2_186 {
            get {
                return ResourceManager.GetString("Health2_186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каждое утро, проснувшись, начинай с мыслей:
        ///«Сегодня мне повезло, — я проснулся.
        ///Я жив, у меня есть эта драгоценная человеческая жизнь, и я не стану тратить её впустую.
        ///Я направлю всю свою энергию на внутреннее развитие,
        ///Чтобы раскрыть свое сердце другим
        ///И достичь просветления во благо всем существам.
        ///Я буду питать лишь добрые помыслы о других.
        ///Я не стану сердиться или думать о них дурное.
        ///Всеми силами буду я приносить пользу другим».
        ///Далай Лама.
        /// </summary>
        internal static string Health2_187 {
            get {
                return ResourceManager.GetString("Health2_187", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы гости на этой планете.
        ///Мы здесь, на 90 или 100 лет, а может и дольше.
        ///За это время мы должны постараться сделать что-то хорошее, что-то полезное.
        ///Если вы поможете другим стать счастливыми,
        ///То откроете для себя истинную цель жизни, её подлинный смысл.
        ///Далай Лама.
        /// </summary>
        internal static string Health2_188 {
            get {
                return ResourceManager.GetString("Health2_188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одна из главных обязанностей врача – научить людей не принимать лекарства. 
        ///УИЛЬЯМ ОСЛЕР, американский терапевт.
        /// </summary>
        internal static string Health2_19 {
            get {
                return ResourceManager.GetString("Health2_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Человек вначале жертвует своим здоровьем для того, чтобы заработать деньги. Потом он тратит деньги на восстановление здоровья. При этом он настолько беспокоится о своем будущем, что никогда не наслаждается настоящим. В результате он не живет ни в настоящем, ни в будущем. Он живет так, как будто никогда не умрет, а умирая, сожалеет о том, что не жил. 
        ///Далай Лама.
        /// </summary>
        internal static string Health2_2 {
            get {
                return ResourceManager.GetString("Health2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cвобода и здоровье имеют одно общее: по-настоящему ценишь их только тогда, когда их не хватает. 
        ///Анри Бек.
        /// </summary>
        internal static string Health2_20 {
            get {
                return ResourceManager.GetString("Health2_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диагностика достигла таких успехов, что здоровых людей практически не осталось. 
        ///Бертран Рассел.
        /// </summary>
        internal static string Health2_21 {
            get {
                return ResourceManager.GetString("Health2_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У хорошего доктора лекарство не в аптеке, а в его собственной голове. 
        ///Василий Осипович Ключевский.
        /// </summary>
        internal static string Health2_22 {
            get {
                return ResourceManager.GetString("Health2_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если больному после разговора с врачом не становится легче, то это не врач. 
        ///Владимир Михайлович Бехтерев.
        /// </summary>
        internal static string Health2_23 {
            get {
                return ResourceManager.GetString("Health2_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отдых необходим. Я могу сделать годовую порцию работы за девять месяцев, но не за двенадцать. 
        ///Джон Пирпонт Морган.
        /// </summary>
        internal static string Health2_24 {
            get {
                return ResourceManager.GetString("Health2_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хороший врач спасает если не от болезни, то хотя бы от плохого врача. 
        ///Жан Поль.
        /// </summary>
        internal static string Health2_25 {
            get {
                return ResourceManager.GetString("Health2_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Счастье - как здоровье: когда его не замечают, значит, оно есть. 
        ///Иван Сергеевич Тургенев.
        /// </summary>
        internal static string Health2_26 {
            get {
                return ResourceManager.GetString("Health2_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В ревматизм и в настоящую любовь не верят до первого приступа. 
        ///Мария фон Эбнер-Эшенбах.
        /// </summary>
        internal static string Health2_27 {
            get {
                return ResourceManager.GetString("Health2_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Единственный способ сохранить здоровье - это есть то, чего не хочешь, пить то, чего не любишь, и делать то, что не нравится. 
        ///Марк Твен.
        /// </summary>
        internal static string Health2_28 {
            get {
                return ResourceManager.GetString("Health2_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У человечества, как и у отдельного человека, с каждым возрастом приходят свои болезни. 
        ///Ральф Уолдо Эмерсон.
        /// </summary>
        internal static string Health2_29 {
            get {
                return ResourceManager.GetString("Health2_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если есть лекарство, то вам не о чем беспокоиться. Вам достаточно принять его. Если же лекарства нет, то к чему беспокойство? Беспокойство лишь усугубляет страдания.
        ///Далай Лама.
        /// </summary>
        internal static string Health2_3 {
            get {
                return ResourceManager.GetString("Health2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От любви и от насморка нет лекарств. Само проходит. 
        ///Станислав Ежи Лец.
        /// </summary>
        internal static string Health2_30 {
            get {
                return ResourceManager.GetString("Health2_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Склероз нельзя вылечить, но о нем можно забыть. 
        ///Фаина Раневская.
        /// </summary>
        internal static string Health2_31 {
            get {
                return ResourceManager.GetString("Health2_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сила и слабость духа - это просто неправильные выражения: в действительности же существует лишь хорошее или плохое состояние органов тела. 
        ///Франсуа де Ларошфуко.
        /// </summary>
        internal static string Health2_32 {
            get {
                return ResourceManager.GetString("Health2_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Болезни души так же возвращаются к нам, как и болезни тела. То, что мы принимаем за выздоровление, обычно оказывается либо кратковременным облегчением старого недуга, либо началом нового. 
        ///Франсуа де Ларошфуко.
        /// </summary>
        internal static string Health2_33 {
            get {
                return ResourceManager.GetString("Health2_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «От чего умер ваш дядя?» – «Он вместо 15 капель Боткина, как прописал доктор, принял 16». 
        ///АНТОН ЧЕХОВ.
        /// </summary>
        internal static string Health2_34 {
            get {
                return ResourceManager.GetString("Health2_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доктор даёт мне две недели жизни. Хорошо бы в августе.
        ///РОННИ ШЕЙКС.
        /// </summary>
        internal static string Health2_35 {
            get {
                return ResourceManager.GetString("Health2_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У каждого человека существует свой собственный способ быть здоровым, который он не может изменять, не подвергая себя риску.
        ///ИММАНУИЛ КАНТ в письме Моисею Мендельсону от 16-го августа 1783.
        /// </summary>
        internal static string Health2_36 {
            get {
                return ResourceManager.GetString("Health2_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ни насыщение, ни голод и ничто другое не хорошо, если преступить меру природы.
        ///Гиппократ.
        /// </summary>
        internal static string Health2_37 {
            get {
                return ResourceManager.GetString("Health2_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Праздность и ничегонеделание влекут за собой порочность и нездоровье — напротив того, устремление ума к чему-либо приносит за собой бодрость, вечно направленную к укреплению жизни.
        ///Гиппократ.
        /// </summary>
        internal static string Health2_38 {
            get {
                return ResourceManager.GetString("Health2_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если будешь следовать природе, то навсегда останешься здоровым.
        ///Пенн Вильям.
        /// </summary>
        internal static string Health2_39 {
            get {
                return ResourceManager.GetString("Health2_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если можешь помочь, помоги. Если нет, хотя бы не вреди. 
        ///Далай Лама.
        /// </summary>
        internal static string Health2_4 {
            get {
                return ResourceManager.GetString("Health2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здоровый дух в здоровом теле — вот краткое, но полное описание счастливого состояния в этом мире.
        ///Джон Локк.
        /// </summary>
        internal static string Health2_40 {
            get {
                return ResourceManager.GetString("Health2_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чего не лечат лекарства, излечивает железо; чего не врачует железо, исцеляет огонь; чего не исцеляет огонь, то следует считать неизлечимым.
        ///Гиппократ.
        /// </summary>
        internal static string Health2_41 {
            get {
                return ResourceManager.GetString("Health2_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как суконщики чистят сукна, выбивая их от пыли, так гимнастика очищает организм.
        ///Свифт Д..
        /// </summary>
        internal static string Health2_42 {
            get {
                return ResourceManager.GetString("Health2_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В здоровом теле - здоровый дух.
        ///Децим Юний Ювенал.
        /// </summary>
        internal static string Health2_43 {
            get {
                return ResourceManager.GetString("Health2_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здоровье — великое дело как для того, кто им пользуется, так и для других.
        ///Томас Карлейль.
        /// </summary>
        internal static string Health2_44 {
            get {
                return ResourceManager.GetString("Health2_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если Вы выглядите как Ваша фотография в загранпаспорте, Вам, вероятно, необходим отдых за границей.
        ///Эрл Уилсон.
        /// </summary>
        internal static string Health2_45 {
            get {
                return ResourceManager.GetString("Health2_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Города нужно строить в деревне, где воздух гораздо лучше.
        ///Анри Мурье.
        /// </summary>
        internal static string Health2_46 {
            get {
                return ResourceManager.GetString("Health2_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Счастье есть продукт здоровья, а потому каждый человек должен стараться, чтобы физические расстройства были не более как исключительными явлениями.
        ///Смайлс С..
        /// </summary>
        internal static string Health2_47 {
            get {
                return ResourceManager.GetString("Health2_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разумный человек приспосабливается к миру, неразумный — упорно пытается приспособить мир к себе.
        ///Неизвестный.
        /// </summary>
        internal static string Health2_48 {
            get {
                return ResourceManager.GetString("Health2_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком многие сейчас тратят деньги, которых они не заработали, на вещи, которые им не нужны, чтобы произвести впечатление на людей, которые им не нравятся.
        ///Уилл Смит.
        /// </summary>
        internal static string Health2_49 {
            get {
                return ResourceManager.GetString("Health2_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Делитесь своими знаниями. Это способ достичь бессмертия. Далай Лама.
        /// </summary>
        internal static string Health2_5 {
            get {
                return ResourceManager.GetString("Health2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Читать между строк полезно - глаза не так устают.
        ///Саша Гитри.
        /// </summary>
        internal static string Health2_50 {
            get {
                return ResourceManager.GetString("Health2_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О бессмертии мечтают миллионы людей — те самые, которые мучительно думают, чем бы занять себя в дождливый воскресные вечер.
        ///Сьюзен Эрц.
        /// </summary>
        internal static string Health2_51 {
            get {
                return ResourceManager.GetString("Health2_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здоровье никогда не может потерять своей цены в глазах человека, потому что и в довольстве, и в роскоши плохо жить без здоровья.
        ///Чернышевский Н. Г..
        /// </summary>
        internal static string Health2_52 {
            get {
                return ResourceManager.GetString("Health2_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разве хоть один человек смог бы поставить босую ногу на раскалённые угли, если бы он не верил в то, что сможет ходить по ним и не обжечься? Конечно же, нет!
        ///Адам Джексон — 10 секретов здоровья.
        /// </summary>
        internal static string Health2_53 {
            get {
                return ResourceManager.GetString("Health2_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если не будешь есть еду как лекарство, то будешь есть лекарство как еду!
        ///Михаил Задорнов.
        /// </summary>
        internal static string Health2_54 {
            get {
                return ResourceManager.GetString("Health2_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Единственная красота, которую я знаю,- это здоровье.
        ///Генрих Гейне.
        /// </summary>
        internal static string Health2_55 {
            get {
                return ResourceManager.GetString("Health2_55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Человеку свойственно по природе своей соблюдать умеренность не только из-за заботы о своем здоровье в будущем, но также из-за хорошего самочувствия настоящем.
        ///Иммануил Кант.
        /// </summary>
        internal static string Health2_56 {
            get {
                return ResourceManager.GetString("Health2_56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каким бы ни было ваше здоровье, его хватит до конца жизни.
        ///Борисов Л..
        /// </summary>
        internal static string Health2_57 {
            get {
                return ResourceManager.GetString("Health2_57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучше всего пахнет тело, которое ничем не пахнет.
        ///Луций Анней Сенека.
        /// </summary>
        internal static string Health2_58 {
            get {
                return ResourceManager.GetString("Health2_58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто, не зная ничего, держит себя как знающий много, тот болен.
        ///Лао Цзы.
        /// </summary>
        internal static string Health2_59 {
            get {
                return ResourceManager.GetString("Health2_59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Любящая атмосфера является основой для вашей жизни. Далай Лама.
        /// </summary>
        internal static string Health2_6 {
            get {
                return ResourceManager.GetString("Health2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исцеление — это дело времени.
        ///Гиппократ.
        /// </summary>
        internal static string Health2_60 {
            get {
                return ResourceManager.GetString("Health2_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто боязливо заботится о том, как бы не потерять жизнь, никогда не будет радоваться ей.
        ///И.Кант.
        /// </summary>
        internal static string Health2_61 {
            get {
                return ResourceManager.GetString("Health2_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы хотим всесторонне развить человека, чтобы он умел хорошо бегать, плавать, быстро и красиво ходить, чтобы у него были все органы в порядке, словом, чтобы он был нормальным, здоровым человеком, готовым к труду и обороне, чтобы параллельно всем физическим качествам правильно развивались и умственные его качества.
        ///Калинин М. И..
        /// </summary>
        internal static string Health2_62 {
            get {
                return ResourceManager.GetString("Health2_62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Многие потеряли здоровье, пытаясь заработать все деньги, которые можно заработать; а потом потеряли все деньги, пытаясь вернуть здоровье..
        /// </summary>
        internal static string Health2_63 {
            get {
                return ResourceManager.GetString("Health2_63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жизнерадостность - это не только признак здоровья, но ещё и самое действенное средство, избавляющее от болезней.
        ///Сэмюэл Смайлс.
        /// </summary>
        internal static string Health2_64 {
            get {
                return ResourceManager.GetString("Health2_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самое важное свойство для физического здоровья представляет бодрость духа. Упадок духа сродни смерти.
        ///Уильям Годвин.
        /// </summary>
        internal static string Health2_65 {
            get {
                return ResourceManager.GetString("Health2_65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Человек должен знать, как помочь себе самому в болезни, имея в виду, что здоровье есть высочайшее богатство человека.
        ///Гиппократ.
        /// </summary>
        internal static string Health2_66 {
            get {
                return ResourceManager.GetString("Health2_66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тщательно заботься о своем здоровье.
        ///Марк Туллий Цицерон.
        /// </summary>
        internal static string Health2_67 {
            get {
                return ResourceManager.GetString("Health2_67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если ты никак не можешь найти время для отдыха, тебе очень скоро придется найти время для лечения.
        ///Джон Уэйнмейкер.
        /// </summary>
        internal static string Health2_68 {
            get {
                return ResourceManager.GetString("Health2_68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не ходи к врачам, если тебе уже нечем помочь им.
        ///Веселин Георгиев.
        /// </summary>
        internal static string Health2_69 {
            get {
                return ResourceManager.GetString("Health2_69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Иногда нужно прислушиваться к себе, наедине. Далай Лама.
        /// </summary>
        internal static string Health2_7 {
            get {
                return ResourceManager.GetString("Health2_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здоровье есть само удовольствие или неизбежно порождает удовольствие, как огонь создает теплоту.
        ///Мор Т..
        /// </summary>
        internal static string Health2_70 {
            get {
                return ResourceManager.GetString("Health2_70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тот факт, что верующий счастливее скептика практически ничем не отличается от того факта, что выпивший человек счастливее трезвого.
        ///Джордж Бернард Шоу.
        /// </summary>
        internal static string Health2_71 {
            get {
                return ResourceManager.GetString("Health2_71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дорогие вы мои, все ваши болезни от нежести вашей: от тепла, от вкусной пищи, от покоя. Не бойтесь холода, он мобилизует, как нынче модно сказывать, защиту организма. Холод кидает в тело гормон здоровья. Пусть каждый покумекает, что ему важнее — дело или малые радости. На все должна быть победа. Человек должен жить в победе; если ее не получишь, грош тебе цена в базарный день… Зачем лечиться, когда можно и должно болезнь в тело не пускать!
        ///Порфирий Корнеевич Иванов.
        /// </summary>
        internal static string Health2_72 {
            get {
                return ResourceManager.GetString("Health2_72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если ваша единственная цель состоит в том, чтобы стать богатым, вы никогда не достигнете её.
        ///Джон Дэвисон Рокфеллер.
        /// </summary>
        internal static string Health2_73 {
            get {
                return ResourceManager.GetString("Health2_73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтоб мудро жизнь прожить, знать надобно немало.
        ///Два важных правила запомни для начала:
        ///Уж лучше голодать, чем что попало есть,
        ///И лучше одному, чем вместе с кем попало.
        ///Омар Хайям.
        /// </summary>
        internal static string Health2_74 {
            get {
                return ResourceManager.GetString("Health2_74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завтрак съешь сам, обед раздели с другом, а ужин отдай врагу!
        ///Народная мудрость.
        /// </summary>
        internal static string Health2_75 {
            get {
                return ResourceManager.GetString("Health2_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пока есть болезнь, будет не только страх, но и надежда.
        ///Сэмюэл Батлер.
        /// </summary>
        internal static string Health2_76 {
            get {
                return ResourceManager.GetString("Health2_76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Береги платье снову, а здоровье смолоду..
        /// </summary>
        internal static string Health2_77 {
            get {
                return ResourceManager.GetString("Health2_77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самое важное свойство для физического здоровья представляет бодрость духа. Упадок духа сродни смерти.
        ///Уильям Годвин.
        /// </summary>
        internal static string Health2_78 {
            get {
                return ResourceManager.GetString("Health2_78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если здоровье плохо - думай о чем-нибудь другом.
        ///Эдуард Бенсон.
        /// </summary>
        internal static string Health2_79 {
            get {
                return ResourceManager.GetString("Health2_79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раз в год отправляйтесь туда, где вы никогда не были раньше. Далай Лама.
        /// </summary>
        internal static string Health2_8 {
            get {
                return ResourceManager.GetString("Health2_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для сохранения здравия, а иначе, для предупреждения нормальных болезней, нет ничего лучше упражнений телесных или движений.
        ///Матвей Яковлевич Мудров.
        /// </summary>
        internal static string Health2_80 {
            get {
                return ResourceManager.GetString("Health2_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одна боль всегда уменьшает другую.
        ///А. П. Чехов.
        /// </summary>
        internal static string Health2_81 {
            get {
                return ResourceManager.GetString("Health2_81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почему так бывает, что состояние больного приличное, а здоровье — никудышнее?
        ///Владимир Туровский.
        /// </summary>
        internal static string Health2_82 {
            get {
                return ResourceManager.GetString("Health2_82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самые красивые и здоровые люди - это люди которых ничего не раздражает.
        ///Г. Лихтемберг.
        /// </summary>
        internal static string Health2_83 {
            get {
                return ResourceManager.GetString("Health2_83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тот прожил долго, кто жил хорошо, а время, потраченное неправильно, не прожито, а упущено.
        ///Т.Фуллер.
        /// </summary>
        internal static string Health2_84 {
            get {
                return ResourceManager.GetString("Health2_84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я его перевязывал, бог его излечил.
        ///Амбруаз Паре.
        /// </summary>
        internal static string Health2_85 {
            get {
                return ResourceManager.GetString("Health2_85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не жарь то, что можно сварить, и не вари то, что можно съесть сырым!
        ///Народная мудрость.
        /// </summary>
        internal static string Health2_86 {
            get {
                return ResourceManager.GetString("Health2_86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучше принять от мудреца яд, чем от подлеца — лекарство.
        ///Омар Хайям.
        /// </summary>
        internal static string Health2_87 {
            get {
                return ResourceManager.GetString("Health2_87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Умирает только хилое и слабое, здоровое и сильное всегда выходит победителем в борьбе за существование.
        ///Чарльз Дарвин.
        /// </summary>
        internal static string Health2_88 {
            get {
                return ResourceManager.GetString("Health2_88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Противодействуй болезни вначале; поздно думать о лекарствах, когда болезнь укоренилась от долгого промедления.
        ///Овидий.
        /// </summary>
        internal static string Health2_89 {
            get {
                return ResourceManager.GetString("Health2_89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тело – багаж, который несёшь всю жизнь. И чем он тяжелее, тем сложней двигаться дальше..
        /// </summary>
        internal static string Health2_9 {
            get {
                return ResourceManager.GetString("Health2_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здоровье дороже богатства.
        ///Джон Рей.
        /// </summary>
        internal static string Health2_90 {
            get {
                return ResourceManager.GetString("Health2_90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to И лучше яд испей из чаши мудреца, чем жизненный бальзам из рук людей негодных.
        ///Омар Хайям.
        /// </summary>
        internal static string Health2_91 {
            get {
                return ResourceManager.GetString("Health2_91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чем тяжелей болезнь, тем явственнее внутренний голос.
        ///Чарльз Лэм.
        /// </summary>
        internal static string Health2_92 {
            get {
                return ResourceManager.GetString("Health2_92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Девять десятых нашего счастья зависят от здоровья.
        ///Шопенгауэр А..
        /// </summary>
        internal static string Health2_93 {
            get {
                return ResourceManager.GetString("Health2_93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Надежда выздороветь - половина выздоровления.
        ///Вольтер.
        /// </summary>
        internal static string Health2_94 {
            get {
                return ResourceManager.GetString("Health2_94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не надо завышать свои обязанности. Однако большинство людей живёт, завышая свои потребности.
        ///Михаил Задорнов.
        /// </summary>
        internal static string Health2_95 {
            get {
                return ResourceManager.GetString("Health2_95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гимнастика, физические упражнения, ходьба должны прочно войти в повседневный быт каждого, кто хочет сохранить работоспособность, здоровье, полноценную и радостную жизнь.
        ///Гипократ.
        /// </summary>
        internal static string Health2_96 {
            get {
                return ResourceManager.GetString("Health2_96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Много главных страниц жизни не было написано из-за халатного отношения к здоровью.
        ///Георгий Александров.
        /// </summary>
        internal static string Health2_97 {
            get {
                return ResourceManager.GetString("Health2_97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не курите сидя на лошади, — один грамм никотина, и вы пойдете пешком.
        ///Валерий Миронов.
        /// </summary>
        internal static string Health2_98 {
            get {
                return ResourceManager.GetString("Health2_98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Под здоровьем нельзя разуметь одно только наружное благосостояние тела, а нужно понимать вообще естественное гармоническое развитие организма и правильное совершение всех его отправлений.
        ///Николай Александрович Добролюбов.
        /// </summary>
        internal static string Health2_99 {
            get {
                return ResourceManager.GetString("Health2_99", resourceCulture);
            }
        }
    }
}
