//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarumaResourcesPortable.LocalizationResources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Luck2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Luck2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DarumaResourcesPortable.LocalizationResources.Luck2", typeof(Luck2).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я этого хочу. Значит, это будет.  
        ///Генри Форд.
        /// </summary>
        internal static string Luck2_0 {
            get {
                return ResourceManager.GetString("Luck2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Урок, который я извлек и которому следую всю жизнь, состоял в том, что надо пытаться, и пытаться, и опять пытаться — но никогда не сдаваться!  
        ///Ричард Бренсон.
        /// </summary>
        internal static string Luck2_1 {
            get {
                return ResourceManager.GetString("Luck2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Способность быть счастливыми и успешными в наших руках.
        ///Шарлотта Бронте.
        /// </summary>
        internal static string Luck2_10 {
            get {
                return ResourceManager.GetString("Luck2_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Успех обычно приходит к тем, кто слишком занят, чтобы искать его». 
        ///ГЕНРИ ДЭВИД ТОРО.
        /// </summary>
        internal static string Luck2_100 {
            get {
                return ResourceManager.GetString("Luck2_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Успех – это 99% неудач». 
        ///СОИЧИРО ХОНДА.
        /// </summary>
        internal static string Luck2_101 {
            get {
                return ResourceManager.GetString("Luck2_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Успех – это не более чем несколько простых правил, соблюдаемых ежедневно, а неудача – это просто несколько ошибок, повторяемых ежедневно. Вместе они составляют то, что приводит нас либо к удаче, либо к поражению». 
        ///ДЖИМ РОН.
        /// </summary>
        internal static string Luck2_102 {
            get {
                return ResourceManager.GetString("Luck2_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Человек должен быть солидным в своём ожидании жизненного успеха. Не нужно метаться». 
        ///АРМЕН ДЖИГАРХАНЯН.
        /// </summary>
        internal static string Luck2_103 {
            get {
                return ResourceManager.GetString("Luck2_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Успешные люди делают то, что неудачники делать не желают». 
        ///КТО-ТО.
        /// </summary>
        internal static string Luck2_104 {
            get {
                return ResourceManager.GetString("Luck2_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Успех ничему не учит. Он только убеждает умных людей, что они не могут проиграть». 
        ///БИЛЛ ГЕЙТС, Esquire, 2006, ноябрь, стр. 182.
        /// </summary>
        internal static string Luck2_105 {
            get {
                return ResourceManager.GetString("Luck2_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Делать обыкновенные вещи необыкновенно хорошо – вот самый короткий путь к успеху». 
        ///ГЕНРИ ДЖОН ХАЙНЦ, основатель корпорации Heinz.
        /// </summary>
        internal static string Luck2_106 {
            get {
                return ResourceManager.GetString("Luck2_106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Я не могу дать вам формулу успеха, но готов предложить формулу неудачи – попробуйте всем понравиться». 
        ///Г. СВОУП, журналист.
        /// </summary>
        internal static string Luck2_107 {
            get {
                return ResourceManager.GetString("Luck2_107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Для успеха необходим досуг. Нужно время, которое безраздельно принадлежит только вам». 
        ///ДЖОРДЖ СОРОС.
        /// </summary>
        internal static string Luck2_108 {
            get {
                return ResourceManager.GetString("Luck2_108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Успех? Это движение от неудачи к неудаче без потери энтузиазма». 
        ///УИНСТОН ЧЕРЧИЛЛЬ.
        /// </summary>
        internal static string Luck2_109 {
            get {
                return ResourceManager.GetString("Luck2_109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to То, что гусеница называет смертью, умелец назовёт бабочкой. 
        ///Ричард Бах.
        /// </summary>
        internal static string Luck2_11 {
            get {
                return ResourceManager.GetString("Luck2_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Добиться успеха не означает, что вы должны сделать что-либо исключительное. Это означает, что вы должны делать то же, что и все, только исключительно хорошо». 
        ///КОЛИН ТЁРНЕР.
        /// </summary>
        internal static string Luck2_110 {
            get {
                return ResourceManager.GetString("Luck2_110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Для достижения успеха надо ставить цели несколько выше, чем те, которые в настоящее время могут быть достигнуты». 
        ///МАКС ПЛАНК.
        /// </summary>
        internal static string Luck2_111 {
            get {
                return ResourceManager.GetString("Luck2_111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Каждому человеку в течение дня предоставляется не менее десяти возможностей изменить свою жизнь. Успех приходит к тому, кто умеет их использовать». 
        ///А. МОРУА.
        /// </summary>
        internal static string Luck2_112 {
            get {
                return ResourceManager.GetString("Luck2_112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Ключ к успеху – в желании. А оно постоянно горит во мне». 
        ///АЛЬ ПАЧИНО.
        /// </summary>
        internal static string Luck2_113 {
            get {
                return ResourceManager.GetString("Luck2_113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Если вы хотите увеличить уровень своего успеха, удвойте количество своих неудач». 
        ///ТОМАС УОТСОН, основатель IBM.
        /// </summary>
        internal static string Luck2_114 {
            get {
                return ResourceManager.GetString("Luck2_114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Мудрец вечно полон тревоги и сомнений, прежде чем что-либо предпринять, но оттого ему всегда и сопутствует успех». 
        ///ЧЖУАН-ЦЗЫ.
        /// </summary>
        internal static string Luck2_115 {
            get {
                return ResourceManager.GetString("Luck2_115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удача не имеет ничего общего с умением, но приносит плоды, которые невозможно отличить от плодов умения.
        ///ИОН из Хиоса.
        /// </summary>
        internal static string Luck2_116 {
            get {
                return ResourceManager.GetString("Luck2_116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На своих ошибках учатся - на чужих делают карьеру.
        ///АЛЕКСАНДР ФЮРСТЕНБЕРГ.
        /// </summary>
        internal static string Luck2_117 {
            get {
                return ResourceManager.GetString("Luck2_117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат – ещё отнюдь не самое важное.
        ///ИОГАНН НЕСТРОЙ.
        /// </summary>
        internal static string Luck2_118 {
            get {
                return ResourceManager.GetString("Luck2_118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Я могу проиграть, но я всегда останусь в выигрыше!»
        ///Из фильма Алена Рене «Прошлым летом в Мариенбаде».
        /// </summary>
        internal static string Luck2_119 {
            get {
                return ResourceManager.GetString("Luck2_119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Нельзя победить того, кто не сдался. 
        ///Бэйд Руфь..
        /// </summary>
        internal static string Luck2_12 {
            get {
                return ResourceManager.GetString("Luck2_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «В жизни вознаграждения всегда пропорциональны риску»..
        /// </summary>
        internal static string Luck2_120 {
            get {
                return ResourceManager.GetString("Luck2_120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Пессимист видит проблему в каждой задаче. Оптимист – задачу в каждой проблеме».
        ///КИМ КЭТТРОЛЛ, звезда «Секса в большом городе», в книге «Найти себя».
        /// </summary>
        internal static string Luck2_121 {
            get {
                return ResourceManager.GetString("Luck2_121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «То, чему сопротивляемся, указывает на то, чего нам недостаёт».
        ///КТО-ТО.
        /// </summary>
        internal static string Luck2_122 {
            get {
                return ResourceManager.GetString("Luck2_122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Нет ничего невозможного, если ты этого хочешь». (Nihil est difficile volenti.)
        ///Римское присловие.
        /// </summary>
        internal static string Luck2_123 {
            get {
                return ResourceManager.GetString("Luck2_123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Чтобы добиться чего-то, необходимо иметь две вещи: план и недостаток времени».
        ///ЛЕОНАРД БЕРНШТЕЙН.
        /// </summary>
        internal static string Luck2_124 {
            get {
                return ResourceManager.GetString("Luck2_124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Тот, кто привык сопровождать, никогда не будет впереди».
        ///МИКЕЛАНДЖЕЛО.
        /// </summary>
        internal static string Luck2_125 {
            get {
                return ResourceManager.GetString("Luck2_125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «В ж-пу обстоятельства, создавайте возможности». 
        ///БРЮС ЛИ, Esquire, 2007, февраль, стр. 128.
        /// </summary>
        internal static string Luck2_126 {
            get {
                return ResourceManager.GetString("Luck2_126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Высокие цели, хотя бы невыполненные, дороже нам низких целей, хотя бы достигнутых». 
        ///ИОГАНН ВОЛЬФГАНГ ГЁТЕ.
        /// </summary>
        internal static string Luck2_127 {
            get {
                return ResourceManager.GetString("Luck2_127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Для того чтобы быстро плыть, надо медленно грести». 
        ///НОРМАН ВИНСЕНТ ПИЛ.
        /// </summary>
        internal static string Luck2_128 {
            get {
                return ResourceManager.GetString("Luck2_128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Тем, кто удручены, что немногому научились, – да обратят они своё внимание на следующее изречение: «На каждой из ступеней ключ находится в самом ищущем». 
        ///ЕЛЕНА БЛАВАТСКАЯ.
        /// </summary>
        internal static string Luck2_129 {
            get {
                return ResourceManager.GetString("Luck2_129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто желает стать успешным – ищет возможности, кто не желает – ищет отговорки.
        /// </summary>
        internal static string Luck2_13 {
            get {
                return ResourceManager.GetString("Luck2_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Я верю в карму в самом глубинном смысле: твоя воля вызывает то, что приходит к тебе». 
        ///ХАНТЕР С. ТОМПСОН, журналист.
        /// </summary>
        internal static string Luck2_130 {
            get {
                return ResourceManager.GetString("Luck2_130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Вы всегда можете получить то, что хотите, но если постараетесь, то, возможно, это будет то, что вам нужно». 
        ///МИК ДЖАГГЕР.
        /// </summary>
        internal static string Luck2_131 {
            get {
                return ResourceManager.GetString("Luck2_131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Не иди по течению, не иди против течения, иди поперёк него, если хочешь достичь берега». 
        ///Изречение китайской философской школы Дао Цзи Бай.
        /// </summary>
        internal static string Luck2_132 {
            get {
                return ResourceManager.GetString("Luck2_132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Сиди спокойно на берегу реки, и мимо проплывёт труп твоего врага». 
        ///КОНФУЦИЙ.
        /// </summary>
        internal static string Luck2_133 {
            get {
                return ResourceManager.GetString("Luck2_133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Будешь носить понемногу – и гору перенесёшь, будешь носить помногу – самого придётся нести». 
        ///Китайская пословица.
        /// </summary>
        internal static string Luck2_134 {
            get {
                return ResourceManager.GetString("Luck2_134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Ошибочно лишь прекращение усилий». 
        ///Восточная мудрость.
        /// </summary>
        internal static string Luck2_135 {
            get {
                return ResourceManager.GetString("Luck2_135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Если не можешь постоянно быть собранным, будь собран хотя бы раз в день». 
        ///ТОМАС А. КЕМПИС.
        /// </summary>
        internal static string Luck2_136 {
            get {
                return ResourceManager.GetString("Luck2_136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Нерешительность – вор возможности». 
        ///ДЖИМ РОН.
        /// </summary>
        internal static string Luck2_137 {
            get {
                return ResourceManager.GetString("Luck2_137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Вы не обязаны быть великим, чтобы начать, но обязаны начать, чтобы стать великим». 
        ///ДЖО САБАХ.
        /// </summary>
        internal static string Luck2_138 {
            get {
                return ResourceManager.GetString("Luck2_138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Господь, мы знаем, кто мы, но мы не знаем, кем мы можем стать». 
        ///ВИЛЬЯМ ШЕКСПИР.
        /// </summary>
        internal static string Luck2_139 {
            get {
                return ResourceManager.GetString("Luck2_139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Любому кораблю в порту будет безопасней, но его строили не для этого.
        ///Грейс Хоппер.
        /// </summary>
        internal static string Luck2_14 {
            get {
                return ResourceManager.GetString("Luck2_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Самое существенное в жизни – это умение в любой момент пожертвовать тем, что мы есть сейчас, ради того, чем мы можем стать». 
        ///ЧАРЛЬЗ ДЕБУА.
        /// </summary>
        internal static string Luck2_140 {
            get {
                return ResourceManager.GetString("Luck2_140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Вы не можете за одну ночь изменить свою жизнь, но можете изменить направление, в котором вы движетесь». 
        ///ДЖИМ РОН, американский бизнес-тренер и мотиватор.
        /// </summary>
        internal static string Luck2_141 {
            get {
                return ResourceManager.GetString("Luck2_141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Возможность получать подобна океану. Проблема в том, что большинство людей подходит к этому океану возможностей с чайной ложкой». 
        ///ДЖИМ РОН.
        /// </summary>
        internal static string Luck2_142 {
            get {
                return ResourceManager.GetString("Luck2_142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Один из способов, чтобы научиться делать что-то правильно, это сделать сначала неправильно». 
        ///ДЖИМ РОН.
        /// </summary>
        internal static string Luck2_143 {
            get {
                return ResourceManager.GetString("Luck2_143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Единственная возможность перевернуть свою жизнь однажды – это изменить свои взгляды». 
        ///ДЖИМ РОН.
        /// </summary>
        internal static string Luck2_144 {
            get {
                return ResourceManager.GetString("Luck2_144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Принятие окончательного решения иногда может выглядеть как гражданская война внутри тебя». 
        ///ДЖИМ РОН.
        /// </summary>
        internal static string Luck2_145 {
            get {
                return ResourceManager.GetString("Luck2_145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Люди чаще капитулируют, чем терпят поражение». 
        ///ГЕНРИ ФОРД.
        /// </summary>
        internal static string Luck2_146 {
            get {
                return ResourceManager.GetString("Luck2_146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Единственный способ определить границы возможного – выйти за эти границы». 
        ///АРТУР КЛАРК.
        /// </summary>
        internal static string Luck2_147 {
            get {
                return ResourceManager.GetString("Luck2_147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Неудача – это возможность в рабочей одежде». 
        ///ГЕНРИ КАЙЗЕР.
        /// </summary>
        internal static string Luck2_148 {
            get {
                return ResourceManager.GetString("Luck2_148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «В серьёзных делах следует заботиться не столько о том, чтобы создать благоприятные возможности, сколько о том, чтобы их не упустить». 
        ///ЛАРОШФУКО.
        /// </summary>
        internal static string Luck2_149 {
            get {
                return ResourceManager.GetString("Luck2_149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Никто не побеждён, пока не признает себя таковым. 
        ///Наполеон Хилл.
        /// </summary>
        internal static string Luck2_15 {
            get {
                return ResourceManager.GetString("Luck2_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Выбери, кем ты будешь, и заплати за это». 
        ///Испанская пословица.
        /// </summary>
        internal static string Luck2_150 {
            get {
                return ResourceManager.GetString("Luck2_150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проблемы нельзя разрешить, следуя тому же образу мыслей, что их породил. 
        ///АЛЬБЕРТ ЭЙНШТЕЙН (ALBERT EINSTEIN).
        /// </summary>
        internal static string Luck2_151 {
            get {
                return ResourceManager.GetString("Luck2_151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Кто колеблется, тот проигрывает». 
        ///Английская пословица.
        /// </summary>
        internal static string Luck2_152 {
            get {
                return ResourceManager.GetString("Luck2_152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Черепаха продвигается только тогда, когда высовывает свою голову». 
        ///ДЖЕЙМС КОНАНТ.
        /// </summary>
        internal static string Luck2_153 {
            get {
                return ResourceManager.GetString("Luck2_153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Иди от себя, но как можно дальше». 
        ///КТО-ТО.
        /// </summary>
        internal static string Luck2_154 {
            get {
                return ResourceManager.GetString("Luck2_154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Мы получаем не то, что заслуживаем, а то, чего добиваемся». 
        ///КТО-ТО.
        /// </summary>
        internal static string Luck2_155 {
            get {
                return ResourceManager.GetString("Luck2_155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Как много дел считались невозможными, пока они не были осуществлены». 
        ///ПЛИНИЙ СТАРШИЙ.
        /// </summary>
        internal static string Luck2_156 {
            get {
                return ResourceManager.GetString("Luck2_156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Живите в соответствии со своим воображением, а не своим прошлым». 
        ///СТИВЕН КОВИ.
        /// </summary>
        internal static string Luck2_157 {
            get {
                return ResourceManager.GetString("Luck2_157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Высота ваших достижений равна глубине ваших убеждений». 
        ///УИЛЛИАМ СКОЛАВИНО.
        /// </summary>
        internal static string Luck2_158 {
            get {
                return ResourceManager.GetString("Luck2_158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Настойчивость – это то, что невозможное делает возможным, а возможное – предопределенным». 
        ///РОБЕРТ ХАЛФ.
        /// </summary>
        internal static string Luck2_159 {
            get {
                return ResourceManager.GetString("Luck2_159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Величайшая слава приходит не к тем, кто забрался выше остальных, а которые продолжали забираться высоко после каждого падения. Нельсон Манделла.
        /// </summary>
        internal static string Luck2_16 {
            get {
                return ResourceManager.GetString("Luck2_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Наша проблема заключается не в недостатке знаний, а в недостатке действий». 
        ///МАРК ХЕТФИЛД.
        /// </summary>
        internal static string Luck2_160 {
            get {
                return ResourceManager.GetString("Luck2_160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Безопасность не является смыслом моей жизни. Большие возможности стоят риска». 
        ///ШИРЛИ ХАФСТЕДЛЕР.
        /// </summary>
        internal static string Luck2_161 {
            get {
                return ResourceManager.GetString("Luck2_161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Высокие цели, даже если никогда не достигаются, очень полезны, они дают возможность человеку прожить вдохновенную жизнь, заставляют развиваться». 
        ///ОЛЬГА МАХОВСКАЯ, психолог, «Известия» от 1 июня 2004, стр. 5.
        /// </summary>
        internal static string Luck2_162 {
            get {
                return ResourceManager.GetString("Luck2_162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Тот, кто почуял ветер перемен, должен строить не щит от ветра, а ветряную мельницу». 
        ///Надпись на китайской вазе.
        /// </summary>
        internal static string Luck2_163 {
            get {
                return ResourceManager.GetString("Luck2_163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Чудеса иногда случаются, но над этим приходится много работать». 
        ///ХАИМ ВЕЙЦМАН.
        /// </summary>
        internal static string Luck2_164 {
            get {
                return ResourceManager.GetString("Luck2_164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Не решайте проблему, а ищите возможности». 
        ///ДЖОРДЖ ГИЛДЕР.
        /// </summary>
        internal static string Luck2_165 {
            get {
                return ResourceManager.GetString("Luck2_165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Выдающиеся достижения совершали только те люди, которые верили, что что-то внутри них выше обстоятельств». 
        ///БРЮС БАРТОН.
        /// </summary>
        internal static string Luck2_166 {
            get {
                return ResourceManager.GetString("Luck2_166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Вы знаете, чего хотите добиться в жизни – просто немного боитесь». 
        ///Из модного журнала.
        /// </summary>
        internal static string Luck2_167 {
            get {
                return ResourceManager.GetString("Luck2_167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Если вы оказались вторым, значит, вы на верном пути». 
        ///ДАМИАН БИРКЕЛ, консультант по карьере.
        /// </summary>
        internal static string Luck2_168 {
            get {
                return ResourceManager.GetString("Luck2_168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Только мёртвая рыба плывет по течению». 
        ///КТО-ТО.
        /// </summary>
        internal static string Luck2_169 {
            get {
                return ResourceManager.GetString("Luck2_169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каждая мечта даётся человеку вместе с силами для того, чтобы её осуществить. 
        ///Ричард Бах.
        /// </summary>
        internal static string Luck2_17 {
            get {
                return ResourceManager.GetString("Luck2_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Лучше зажечь свечу, чем проклинать темноту». 
        ///Китайская пословица.
        /// </summary>
        internal static string Luck2_170 {
            get {
                return ResourceManager.GetString("Luck2_170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Неудачи получаются в результате страха, покоя, изнеженности и беспечности. Устранение страха создаёт уверенность и изобилие. Встаньте и вооружитесь, пусть слабые получают милостыню!» 
        ///ГЕНРИ ФОРД.
        /// </summary>
        internal static string Luck2_171 {
            get {
                return ResourceManager.GetString("Luck2_171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Неудача не преступление; преступно ставить перед собой цели ниже своих возможностей». 
        ///ДЖЕЙМС РАССЕЛ ЛОУЭЛЛ, американский дипломат и литератор.
        /// </summary>
        internal static string Luck2_172 {
            get {
                return ResourceManager.GetString("Luck2_172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Отстаивая свои ограничения, ты лишаешь себя всемогущества». 
        ///РИЧАРД БАХ.
        /// </summary>
        internal static string Luck2_173 {
            get {
                return ResourceManager.GetString("Luck2_173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Если можешь стать орлом, не стремись стать первым среди галок».
        ///ПИФАГОР.
        /// </summary>
        internal static string Luck2_174 {
            get {
                return ResourceManager.GetString("Luck2_174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Подражание – неплохое учебное судно; однако, никогда не развеваться над ним адмиральскому флагу». 
        ///ШРИ АУРОБИНДО.
        /// </summary>
        internal static string Luck2_175 {
            get {
                return ResourceManager.GetString("Luck2_175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «То, как высоко вы поднимаетесь, во многом определяется тем, как высоко вы хотите забраться». 
        ///БРАЙАН ТРЕЙСИ.
        /// </summary>
        internal static string Luck2_176 {
            get {
                return ResourceManager.GetString("Luck2_176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Недалекие люди верят в удачу, мудрые и сильные верят в причину и следствие». 
        ///РАЛЬФ УОЛДО ЭМЕРСОН.
        /// </summary>
        internal static string Luck2_177 {
            get {
                return ResourceManager.GetString("Luck2_177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Если вы не первая собака в упряжке, пейзаж перед вашими глазами никогда не меняется». 
        ///БАДДИ РИАН, главный тренер Phoenix Cardinals, «Промышленный вестник», 2004, №3, стр. 64.
        /// </summary>
        internal static string Luck2_178 {
            get {
                return ResourceManager.GetString("Luck2_178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Проблема в том, что не рискуя, рискуешь в сто раз больше». 
        ///ЙОНГ.
        /// </summary>
        internal static string Luck2_179 {
            get {
                return ResourceManager.GetString("Luck2_179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь в миллион километров начинается с первого маленького шага. Лао Цзы.
        /// </summary>
        internal static string Luck2_18 {
            get {
                return ResourceManager.GetString("Luck2_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Нельзя обскакать кого-то на карусели». 
        ///ХАРУКИ МУРАКАМИ, «Страна чудес без тормозов и Конец света».
        /// </summary>
        internal static string Luck2_180 {
            get {
                return ResourceManager.GetString("Luck2_180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Чтобы добраться до источника, приходится всё время плыть против течения». 
        ///СТАНИСЛАВ ЕЖИ ЛЕЦ.
        /// </summary>
        internal static string Luck2_181 {
            get {
                return ResourceManager.GetString("Luck2_181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Если у вас есть мужество начать, у вас есть мужество для того, чтобы преуспеть». 
        ///ДЭВИД УИСКОТ.
        /// </summary>
        internal static string Luck2_182 {
            get {
                return ResourceManager.GetString("Luck2_182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Если мы обращены в сторону правильного направления, то всё, что нам необходимо делать, – это продолжать двигаться вперёд». 
        ///Буддийская пословица.
        /// </summary>
        internal static string Luck2_183 {
            get {
                return ResourceManager.GetString("Luck2_183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Они могут, потому что они думают, что могут». 
        ///ВЕРГИЛИЙ.
        /// </summary>
        internal static string Luck2_184 {
            get {
                return ResourceManager.GetString("Luck2_184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Если делаешь, то не бойся. Если боишься, то не делай». 
        ///ЧИНГИСХАН.
        /// </summary>
        internal static string Luck2_185 {
            get {
                return ResourceManager.GetString("Luck2_185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Упади семь раз, поднимись восемь». 
        ///Китайская пословица.
        /// </summary>
        internal static string Luck2_186 {
            get {
                return ResourceManager.GetString("Luck2_186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Ошибайтесь, ошибайтесь больше, ошибайтесь лучше». 
        ///САМУЭЛЬ БЕККЕТ.
        /// </summary>
        internal static string Luck2_187 {
            get {
                return ResourceManager.GetString("Luck2_187", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Великие дела вершатся не сверхусилиями, а упорством». 
        ///ЕЛЕНА БЛАВАТСКАЯ.
        /// </summary>
        internal static string Luck2_188 {
            get {
                return ResourceManager.GetString("Luck2_188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Кот в перчатках мышь не поймает». 
        ///БЕНДЖАМИН ФРАНКЛИН.
        /// </summary>
        internal static string Luck2_189 {
            get {
                return ResourceManager.GetString("Luck2_189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если Вы верите в то, что сможете добиться успеха, и если думаете, что не сможете, то и там и там Вы правы. 
        ///Генри Форд.
        /// </summary>
        internal static string Luck2_19 {
            get {
                return ResourceManager.GetString("Luck2_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Миллионеры – это обычные люди, которые когда-то приняли решение добиться из ряда вон выходящих результатов». 
        ///КОЛИН ТЁРНЕР.
        /// </summary>
        internal static string Luck2_190 {
            get {
                return ResourceManager.GetString("Luck2_190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Так устроена жизнь, что каждое препятствие – указатель наиболее верного пути – укрепляет нашу решимость и преподносит нам важный урок. Наши главные ошибки – это невыученные уроки». 
        ///ПОЛЬ ВАЙНЦВАЙГ.
        /// </summary>
        internal static string Luck2_191 {
            get {
                return ResourceManager.GetString("Luck2_191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Чтобы оставаться на одном месте, нужно бежать, а чтобы двигаться, нужно бежать очень быстро». 
        ///Правило Чёрной Королевы.
        /// </summary>
        internal static string Luck2_192 {
            get {
                return ResourceManager.GetString("Luck2_192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Каждый человек – стакан воды, наполненный до краев, абсолютное тело. Вкладывая в него что-то новое, необходимо освободить какую-то часть пространства. Вылить часть воды из собственного стакана – победа над собой, и чем больше таких побед, тем динамичнее развитие личности». 
        ///ГЕННАДИЙ АБРАМОВ, театральный хореограф, «Искусство кино», 2001, № 2, стр. 135.
        /// </summary>
        internal static string Luck2_193 {
            get {
                return ResourceManager.GetString("Luck2_193", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ничто так не портит цель, как попадание.
        ///Приписывается НИКОЛАЮ ФОМЕНКО.
        /// </summary>
        internal static string Luck2_194 {
            get {
                return ResourceManager.GetString("Luck2_194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы изменить свою жизнь, ехать куда-то необязательно, но важно сдвинуться с места..
        /// </summary>
        internal static string Luck2_195 {
            get {
                return ResourceManager.GetString("Luck2_195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Каштанка, это успех!» 
        ///АЙГИ-старший – Айги-младшему.
        /// </summary>
        internal static string Luck2_196 {
            get {
                return ResourceManager.GetString("Luck2_196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Кирпичные стенки» показывают вам ваше предназначение, они отделяют вас от людей, которые недостаточно сильно хотят исполнить свою мечту.
        ///РЭНДИ ПОШ. Цит. по: The New Times, 2008, № 25, стр. 55.
        /// </summary>
        internal static string Luck2_197 {
            get {
                return ResourceManager.GetString("Luck2_197", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для того чтобы увидеть берега Нового Света, нужно иметь отвагу покинуть из виду берега Старого Света.
        ///АНДРЕ ЖИД.
        /// </summary>
        internal static string Luck2_198 {
            get {
                return ResourceManager.GetString("Luck2_198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увидев, сколько людей тебя опередило, подумай о том, сколько их отстало.
        ///ФРИДРИХ III.
        /// </summary>
        internal static string Luck2_199 {
            get {
                return ResourceManager.GetString("Luck2_199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наш большой недостаток в том, что мы слишком быстро опускаем руки. Наиболее верный путь к успеху – все время пробовать еще один раз. 
        ///Томас Эдисон.
        /// </summary>
        internal static string Luck2_2 {
            get {
                return ResourceManager.GetString("Luck2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше благосостояние зависит от Ваших действий. 
        ///Джон Рокфеллер.
        /// </summary>
        internal static string Luck2_20 {
            get {
                return ResourceManager.GetString("Luck2_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неудачник не тот, кто не имел шанса, а тот, кто шанс получил и им не воспользовался.
        ///Татьяна в романе ОЛЬГИ СЛАВНИКОВОЙ «2017».
        /// </summary>
        internal static string Luck2_200 {
            get {
                return ResourceManager.GetString("Luck2_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В жизни только то интересно и выгодно, что человек устраивает сам.
        ///Анфилогов в романе ОЛЬГИ СЛАВНИКОВОЙ «2017».
        /// </summary>
        internal static string Luck2_201 {
            get {
                return ResourceManager.GetString("Luck2_201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Борьба – обязательное условие победы..
        /// </summary>
        internal static string Luck2_202 {
            get {
                return ResourceManager.GetString("Luck2_202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неудача – это план природы подготовить тебя к большей ответственности..
        /// </summary>
        internal static string Luck2_203 {
            get {
                return ResourceManager.GetString("Luck2_203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Воля – это то, что заставляет тебя побеждать, когда твой рассудок говорит тебе, что ты повержен. 
        ///КАРЛОС КАСТАНЕДА.
        /// </summary>
        internal static string Luck2_204 {
            get {
                return ResourceManager.GetString("Luck2_204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оказывается, всё получается, если попробовать..
        /// </summary>
        internal static string Luck2_205 {
            get {
                return ResourceManager.GetString("Luck2_205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы хотите быть богатым и при этом ничего не менять, вынужден вас огорчить: так не бывает.
        ///ТИМ ХАРФОРД, «Экономист под прикрытием».
        /// </summary>
        internal static string Luck2_206 {
            get {
                return ResourceManager.GetString("Luck2_206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравляю вас с будущими неудачами. 
        ///ВИКТОР ШКЛОВСКИЙ.
        /// </summary>
        internal static string Luck2_207 {
            get {
                return ResourceManager.GetString("Luck2_207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не оглядывайся – возможно, за тобой погоня. 
        ///Американская поговорка.
        /// </summary>
        internal static string Luck2_208 {
            get {
                return ResourceManager.GetString("Luck2_208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы поймать рыбу, надо думать о рыбе.
        ///Английская поговорка.
        /// </summary>
        internal static string Luck2_209 {
            get {
                return ResourceManager.GetString("Luck2_209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главное условие успеха, есть терпение. 
        ///Лев Толстой.
        /// </summary>
        internal static string Luck2_21 {
            get {
                return ResourceManager.GetString("Luck2_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to То, что казалось никому не под силу, всегда кто-то сделает первым..
        /// </summary>
        internal static string Luck2_210 {
            get {
                return ResourceManager.GetString("Luck2_210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучше попробовать и сожалеть, чем сожалеть, что никогда не пробовал..
        /// </summary>
        internal static string Luck2_211 {
            get {
                return ResourceManager.GetString("Luck2_211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если мне не везёт, я везу себя сам..
        /// </summary>
        internal static string Luck2_212 {
            get {
                return ResourceManager.GetString("Luck2_212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если тебе плюют в спину, значит, ты впереди!.
        /// </summary>
        internal static string Luck2_213 {
            get {
                return ResourceManager.GetString("Luck2_213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет ничего более стимулирующего, чем когда всё идёт не так, как надо. 
        ///Шерлок Холмс в фильме «Шерлок Холмс» режиссёра Гая Ричи.
        /// </summary>
        internal static string Luck2_214 {
            get {
                return ResourceManager.GetString("Luck2_214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Человек, которому повезло – тот кто просто сделал то, что другие только собирались. 
        ///Жюль Ренар.
        /// </summary>
        internal static string Luck2_22 {
            get {
                return ResourceManager.GetString("Luck2_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто не борется со своими страхами каждый день, Тот не познает секреты успеха. 
        ///Ральф Эмельсон.
        /// </summary>
        internal static string Luck2_23 {
            get {
                return ResourceManager.GetString("Luck2_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если Вы хотите быть более успешным и удачливым, тогда делайте больше. 
        ///Брайан Трейси.
        /// </summary>
        internal static string Luck2_24 {
            get {
                return ResourceManager.GetString("Luck2_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Богатство измеряется количеством дней, которые можно прожить не работая. 
        ///Б. Фуллер.
        /// </summary>
        internal static string Luck2_25 {
            get {
                return ResourceManager.GetString("Luck2_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не пытайтесь научиться свинью петь. Вы тратите своё драгоценное время и раздражаете свинью. 
        ///Ким Кийосаки.
        /// </summary>
        internal static string Luck2_26 {
            get {
                return ResourceManager.GetString("Luck2_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия не всегда приводят к счастью, но бездействие не приведёт точно. 
        ///Бенджамин Дизраэли.
        /// </summary>
        internal static string Luck2_27 {
            get {
                return ResourceManager.GetString("Luck2_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успеха добиваются те, кто не думают о поражении. 
        ///Коко Шанель.
        /// </summary>
        internal static string Luck2_28 {
            get {
                return ResourceManager.GetString("Luck2_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Везение – это результат тщательной подготовки, невезение – результат халатности. 
        ///Роберт Хайнлайн.
        /// </summary>
        internal static string Luck2_29 {
            get {
                return ResourceManager.GetString("Luck2_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для успеха не надо быть умнее других, надо просто быть на день быстрее большинства.  
        ///Лео Сцилард.
        /// </summary>
        internal static string Luck2_3 {
            get {
                return ResourceManager.GetString("Luck2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Если Вы находитесь в темноте и видите лучик света, то не надо рассуждать о том, есть ли смысл идти на него. Сидеть в темноте точно не имеет смысла. 
        ///Виктор Пелевин.
        /// </summary>
        internal static string Luck2_30 {
            get {
                return ResourceManager.GetString("Luck2_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь осторожнее со своими желаниями, они могут сбыться.
        /// </summary>
        internal static string Luck2_31 {
            get {
                return ResourceManager.GetString("Luck2_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы есть то, что мы делаем..
        /// </summary>
        internal static string Luck2_32 {
            get {
                return ResourceManager.GetString("Luck2_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to То, что адаптируется – будет сильным и будет жить, а то, что не меняется и закрывается – умрёт. 
        ///Лао Цзы.
        /// </summary>
        internal static string Luck2_33 {
            get {
                return ResourceManager.GetString("Luck2_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наивысшая преграда перед успехов – это страх провала. 
        ///Свен Эриксон.
        /// </summary>
        internal static string Luck2_34 {
            get {
                return ResourceManager.GetString("Luck2_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех – это очень просто, делайте то, что считаете нужным, тогда когда считаете необходимым. 
        ///Арнольд Глазго.
        /// </summary>
        internal static string Luck2_35 {
            get {
                return ResourceManager.GetString("Luck2_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы стать успешным нужны только две вещи: невежество и уверенность в себе. 
        ///Марк Твен.
        /// </summary>
        internal static string Luck2_36 {
            get {
                return ResourceManager.GetString("Luck2_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Победа будет слаще, если Вы познали горечь поражения.
        /// Малкольм Форбс.
        /// </summary>
        internal static string Luck2_37 {
            get {
                return ResourceManager.GetString("Luck2_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех измеряется не тем, что Вы выполняете, а тем сопротивлением, которое Вы преодолеваете. 
        ///Орисон Марден.
        /// </summary>
        internal static string Luck2_38 {
            get {
                return ResourceManager.GetString("Luck2_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для достижения успеха отношение так же важно, как и способности. Гарри Банкс.
        /// </summary>
        internal static string Luck2_39 {
            get {
                return ResourceManager.GetString("Luck2_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самым важным слагаемым формулы успеха является умение ладить с людьми. 
        ///Теодор Рузвельт.
        /// </summary>
        internal static string Luck2_4 {
            get {
                return ResourceManager.GetString("Luck2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ждать успеха без усердной работы равносильно тому, чтобы ждать урожая, если ничего не было посеяно.  
        ///Девид Блайн.
        /// </summary>
        internal static string Luck2_40 {
            get {
                return ResourceManager.GetString("Luck2_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для того, чтобы достичь успеха Вам нужна идея, которая будет Вас вдохновлять, за которую Вы будете держаться, которая будет Вас подталкивать. 
        ///Тони Дорсетт.
        /// </summary>
        internal static string Luck2_41 {
            get {
                return ResourceManager.GetString("Luck2_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех – это путь, а не пункт назначения. 
        ///Бен Суитленд.
        /// </summary>
        internal static string Luck2_42 {
            get {
                return ResourceManager.GetString("Luck2_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы могли бы запомнить, что никто не поможет Вам, кроме Вас самих. Наполеон Хилл..
        /// </summary>
        internal static string Luck2_43 {
            get {
                return ResourceManager.GetString("Luck2_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шесть составляющих ключа к успеху: искренность, личностная целостность, скромность, вежливость, мудрость, милосердие. 
        ///Уильям Меннингер.
        /// </summary>
        internal static string Luck2_44 {
            get {
                return ResourceManager.GetString("Luck2_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Никогда не поздно стать тем, кем тебе хочется быть. 
        ///Джордж Элиот.
        /// </summary>
        internal static string Luck2_45 {
            get {
                return ResourceManager.GetString("Luck2_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Терпение, настойчивость и пот, вот непревзойдённое сочетание для успеха. 
        ///Наполеон Хилл.
        /// </summary>
        internal static string Luck2_46 {
            get {
                return ResourceManager.GetString("Luck2_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех это наука, если у вас есть условия, вы получите результат. 
        ///Оскар Уайльд.
        /// </summary>
        internal static string Luck2_47 {
            get {
                return ResourceManager.GetString("Luck2_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Собраться вместе есть начало. Держаться вместе есть прогресс. Работать вместе есть успех. 
        ///Генри Форд.
        /// </summary>
        internal static string Luck2_48 {
            get {
                return ResourceManager.GetString("Luck2_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех зависит от предварительной подготовки, и без такой подготовки обязательно будет неудача. 
        ///Конфуций.
        /// </summary>
        internal static string Luck2_49 {
            get {
                return ResourceManager.GetString("Luck2_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех ничему не учит. Он только убеждает умных людей, что они не могут проиграть. 
        ///Билл Гейтс.
        /// </summary>
        internal static string Luck2_5 {
            get {
                return ResourceManager.GetString("Luck2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Развивайте успех из неудач. Препятствия и неудачи есть два вернейших ступеней к успеху. 
        ///Дейл Карнеги.
        /// </summary>
        internal static string Luck2_50 {
            get {
                return ResourceManager.GetString("Luck2_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы могли бы хорошо запомнить, что ничто не может принести вам успех, кроме вас. 
        ///Наполеон Хилл.
        /// </summary>
        internal static string Luck2_51 {
            get {
                return ResourceManager.GetString("Luck2_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Играйте, чтобы победить. Успех – основной залог счастливой жизни, хороших отношений и жизни в статусе человека, которым вы хотели бы быть. 
        ///Марша Петри Сью.
        /// </summary>
        internal static string Luck2_52 {
            get {
                return ResourceManager.GetString("Luck2_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Между успехом и неудачей лежит пропасть, имя которой у меня нет времени. 
        ///Франклин Филд.
        /// </summary>
        internal static string Luck2_53 {
            get {
                return ResourceManager.GetString("Luck2_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тот, кто хочет видеть результаты своего труда немедленно, должен идти в сапожники.
        ///А. Эйнштейн.
        /// </summary>
        internal static string Luck2_54 {
            get {
                return ResourceManager.GetString("Luck2_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Никогда не упускайте из виду тот факт, что самый важный критерий вашего успеха - это то, как вы относитесь к другим людям. 
        ///Барбара Буш.
        /// </summary>
        internal static string Luck2_55 {
            get {
                return ResourceManager.GetString("Luck2_55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какой бы ни была ваша цель, вы сможете ее достигнуть, если только захотите потрудиться.
        ///Опра Уинфри.
        /// </summary>
        internal static string Luck2_56 {
            get {
                return ResourceManager.GetString("Luck2_56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какая польза человеку, если он приобретет весь мир, а душе своей повредит?
        ///Евангелие от Матфея 16:26.
        /// </summary>
        internal static string Luck2_57 {
            get {
                return ResourceManager.GetString("Luck2_57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За одну ночь нельзя изменить жизнь, но можно изменить свои мысли так, что они навсегда изменят твою жизнь.
        ///Джерард Своуп.
        /// </summary>
        internal static string Luck2_58 {
            get {
                return ResourceManager.GetString("Luck2_58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будь тем, чем другие не были..
        /// </summary>
        internal static string Luck2_59 {
            get {
                return ResourceManager.GetString("Luck2_59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех — это движение от неудачи к неудаче без потери энтузиазма. 
        ///Уинстон Черчилль.
        /// </summary>
        internal static string Luck2_6 {
            get {
                return ResourceManager.GetString("Luck2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы должны уже сегодня относиться к себе как к человеку, добившемуся успеха. 
        ///ДЖИМ РОН.
        /// </summary>
        internal static string Luck2_60 {
            get {
                return ResourceManager.GetString("Luck2_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы работаете над поставленными целями, то эти цели будут работать на вас. 
        ///ДЖИМ РОН.
        /// </summary>
        internal static string Luck2_61 {
            get {
                return ResourceManager.GetString("Luck2_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если ты можешь это представить – ты можешь этого добиться..
        /// </summary>
        internal static string Luck2_62 {
            get {
                return ResourceManager.GetString("Luck2_62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если хочешь иметь то, чего никогда не имел, нужно делать то, чего никогда не делал..
        /// </summary>
        internal static string Luck2_63 {
            get {
                return ResourceManager.GetString("Luck2_63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оптимист видит возможность в каждой опасности, пессимист видит опасность в каждой возможности..
        /// </summary>
        internal static string Luck2_64 {
            get {
                return ResourceManager.GetString("Luck2_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пока ты держишься за свою «стабильность», кто-то рядом воплощает в жизнь твои мечты..
        /// </summary>
        internal static string Luck2_65 {
            get {
                return ResourceManager.GetString("Luck2_65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рискуй ежедневно, и твои мечты станут реальностью..
        /// </summary>
        internal static string Luck2_66 {
            get {
                return ResourceManager.GetString("Luck2_66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самое страшное – это не «снова не получается». Самое страшное – это «я больше не хочу пробовать»..
        /// </summary>
        internal static string Luck2_67 {
            get {
                return ResourceManager.GetString("Luck2_67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только те, кто не боятся больших неудач, смогут достичь большого успеха. 
        ///РОБЕРТ КЕННЕДИ.
        /// </summary>
        internal static string Luck2_68 {
            get {
                return ResourceManager.GetString("Luck2_68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тот, кто твёрдо уверен в своих желаниях и отваживается жить так, как мечтает, неизбежно и внезапно встретится со своим успехом..
        /// </summary>
        internal static string Luck2_69 {
            get {
                return ResourceManager.GetString("Luck2_69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я не думаю, что есть какое-либо другое качество столь существенное для любого вида успеха, как настойчивость. 
        ///Дж. Рокфеллер.
        /// </summary>
        internal static string Luck2_7 {
            get {
                return ResourceManager.GetString("Luck2_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удача – это умение использовать каждый шанс..
        /// </summary>
        internal static string Luck2_70 {
            get {
                return ResourceManager.GetString("Luck2_70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех – это сумма маленьких достижений, повторяющихся день изо дня. 
        ///Р. КОЛЛЕР (R. COLLIER).
        /// </summary>
        internal static string Luck2_71 {
            get {
                return ResourceManager.GetString("Luck2_71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех никогда не приходит один. С ним приходят завистники и соавторы..
        /// </summary>
        internal static string Luck2_72 {
            get {
                return ResourceManager.GetString("Luck2_72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех создаётся не способностью, а желанием. 
        ///РИЧАРД ДЕННИ.
        /// </summary>
        internal static string Luck2_73 {
            get {
                return ResourceManager.GetString("Luck2_73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я не знаю ключа от успеха, но ключ от неудачи – это стремление всем понравиться. 
        ///Б. КОСБИ (B. COSBY).
        /// </summary>
        internal static string Luck2_74 {
            get {
                return ResourceManager.GetString("Luck2_74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фунт мужества стоит тонны удачи..
        /// </summary>
        internal static string Luck2_75 {
            get {
                return ResourceManager.GetString("Luck2_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех – это лестница, на которую не взобраться, держа руки в карманах..
        /// </summary>
        internal static string Luck2_76 {
            get {
                return ResourceManager.GetString("Luck2_76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ты не можешь ни выиграть, ни проиграть до тех пор, пока не участвуешь в гонках. 
        ///ДЭВИД БОУИ.
        /// </summary>
        internal static string Luck2_77 {
            get {
                return ResourceManager.GetString("Luck2_77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только те, кто предпринимают абсурдные попытки, смогут достичь невозможного. 
        ///АЛЬБЕРТ ЭЙНШТЕЙН.
        /// </summary>
        internal static string Luck2_78 {
            get {
                return ResourceManager.GetString("Luck2_78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to То, что вы получаете, достигая своих целей, не так важно, как то, кем вы становитесь, достигая своих целей. 
        ///З. ЗИГЛАР (Z. ZIGLAR).
        /// </summary>
        internal static string Luck2_79 {
            get {
                return ResourceManager.GetString("Luck2_79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех — это не столько то, что мы имеем, сколько то, кем мы становимся в результате.
        ///Джим Рон.
        /// </summary>
        internal static string Luck2_8 {
            get {
                return ResourceManager.GetString("Luck2_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страшно не упасть, а не подняться..
        /// </summary>
        internal static string Luck2_80 {
            get {
                return ResourceManager.GetString("Luck2_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Секрет успеха состоит в искренности: если вы научитесь её имитировать, для вас не будет ничего невозможного..
        /// </summary>
        internal static string Luck2_81 {
            get {
                return ResourceManager.GetString("Luck2_81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наши неудачи поучительнее наших удач. 
        ///ГЕНРИ ФОРД.
        /// </summary>
        internal static string Luck2_82 {
            get {
                return ResourceManager.GetString("Luck2_82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мир принадлежит оптимистам, пессимисты – всего лишь зрители..
        /// </summary>
        internal static string Luck2_83 {
            get {
                return ResourceManager.GetString("Luck2_83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каждый раз нужно прыгать со скалы и отращивать крылья по пути вниз. 
        ///РЭЙ БРЭДБЕРИ.
        /// </summary>
        internal static string Luck2_84 {
            get {
                return ResourceManager.GetString("Luck2_84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для первого шага достаточно веры. Не обязательно видеть всю лестницу, чтобы сделать первый шаг. 
        ///МАРТИН ЛЮТЕР КИНГ.
        /// </summary>
        internal static string Luck2_85 {
            get {
                return ResourceManager.GetString("Luck2_85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Где воля напряглась, как тетива, там муравей одолевает льва..
        /// </summary>
        internal static string Luck2_86 {
            get {
                return ResourceManager.GetString("Luck2_86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для первого шага достаточно веры. Не обязательно видеть всю лестницу, чтобы сделать первый шаг. 
        ///МАРТИН ЛЮТЕР КИНГ.
        /// </summary>
        internal static string Luck2_87 {
            get {
                return ResourceManager.GetString("Luck2_87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Секрет успеха – знать то, что никто ещё не знает. 
        ///АРИСТОТЕЛЬ ОНАССИС (ARISTOTLE ONASSIS).
        /// </summary>
        internal static string Luck2_88 {
            get {
                return ResourceManager.GetString("Luck2_88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы подкова принесла удачу, нужно вкалывать как лошадь..
        /// </summary>
        internal static string Luck2_89 {
            get {
                return ResourceManager.GetString("Luck2_89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Делая счастливее других, мы делаем счастливее себя.
        ///Платон.
        /// </summary>
        internal static string Luck2_9 {
            get {
                return ResourceManager.GetString("Luck2_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пессимист видит проблемы в возможностях, в то время как оптимист видит возможности в проблемах. 
        ///УИНСТОН ЧЕРЧИЛЛЬ (WINSTON CHURCHILL).
        /// </summary>
        internal static string Luck2_90 {
            get {
                return ResourceManager.GetString("Luck2_90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы должны себе и обществу – нарушать правила и пробовать что-то новое..
        /// </summary>
        internal static string Luck2_91 {
            get {
                return ResourceManager.GetString("Luck2_91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В моей манере было расширяться, а не передвигаться. На мой взгляд, лестница к успеху ведёт скорее сразу во все стороны, а не наверх.
        ///ЭНДИ УОРХОЛ в мемуарах «Попизм. Уорхоловские 60-е», записанных Пэт Хэкетт.
        /// </summary>
        internal static string Luck2_92 {
            get {
                return ResourceManager.GetString("Luck2_92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех – это путь, а не цель.
        ///КТО-ТО.
        /// </summary>
        internal static string Luck2_93 {
            get {
                return ResourceManager.GetString("Luck2_93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будьте готовы: удача – это когда готовность встречается с возможностью.
        ///РЭНДИ ПОШ. Цит. по: The New Times, 2008, № 25, стр. 55.
        /// </summary>
        internal static string Luck2_94 {
            get {
                return ResourceManager.GetString("Luck2_94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех - не окончателен, неудачи - не фатальны: значение имеет лишь мужество продолжать.
        ///УИНСТОН ЧЕЧИЛЛЬ.
        /// </summary>
        internal static string Luck2_95 {
            get {
                return ResourceManager.GetString("Luck2_95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я не мог дождаться успеха и пустился в путь без него.
        ///ДЖОНАТАН ВИНТЕРС.
        /// </summary>
        internal static string Luck2_96 {
            get {
                return ResourceManager.GetString("Luck2_96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самосовершенствование важней успеха.
        ///БОРИС ЖУТОВСКИЙ, художник. Цит. по: The New Times, 2007, № 44, стр. 47.
        /// </summary>
        internal static string Luck2_97 {
            get {
                return ResourceManager.GetString("Luck2_97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех как следствие трудолюбия – обывательский идеал. 
        ///УОЛЛЕС СТИВЕНС.
        /// </summary>
        internal static string Luck2_98 {
            get {
                return ResourceManager.GetString("Luck2_98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «Я намного больше научился у неудачи, чем у успеха, который отнимает очень много энергии и сил».
        ///КЛОД ЛЕЛУШ – Арине Абросимовой в интервью «Любимчик Бога». «Город Аэропорт» (официальное издание аэропорта «Шереметьево»), 2007, № 4, стр. 14.
        /// </summary>
        internal static string Luck2_99 {
            get {
                return ResourceManager.GetString("Luck2_99", resourceCulture);
            }
        }
    }
}
