//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarumaResourcesPortable.LocalizationResources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Rich2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rich2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DarumaResourcesPortable.LocalizationResources.Rich2", typeof(Rich2).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Многие люди предпочитают иметь немножко денег и немножко счастья, чем опозориться, рискнув погнаться за всем, что может предложить жизнь.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_0 {
            get {
                return ResourceManager.GetString("Rich2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если бы у вас ничего не было - ни денег, ни работы, ни еды, ни жилья - что бы вы стали делать? 
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_1 {
            get {
                return ResourceManager.GetString("Rich2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прекратите хныкать, жаловаться и вести себя как дети.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_10 {
            get {
                return ResourceManager.GetString("Rich2_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жадный всегда беден. 
        ///Петрарка.
        /// </summary>
        internal static string Rich2_100 {
            get {
                return ResourceManager.GetString("Rich2_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бедняку не хватает многого, алчному - решительно всего. Публилий Сир.
        /// </summary>
        internal static string Rich2_101 {
            get {
                return ResourceManager.GetString("Rich2_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбереженная копейка - копейка заработанная. 
        ///Английская поговорка.
        /// </summary>
        internal static string Rich2_102 {
            get {
                return ResourceManager.GetString("Rich2_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для умных, деньги средство, для дураков - цель. 
        ///А. Декурсель.
        /// </summary>
        internal static string Rich2_103 {
            get {
                return ResourceManager.GetString("Rich2_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Человеку без денег трудно оставаться порядочным. 
        ///Б. Франклин.
        /// </summary>
        internal static string Rich2_104 {
            get {
                return ResourceManager.GetString("Rich2_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто жертвует чем то на смертном одре, тот дарит из кармана наследников..
        /// </summary>
        internal static string Rich2_105 {
            get {
                return ResourceManager.GetString("Rich2_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Есть люди что нуждаются обладая богатством, это самый страшный вид нищеты. 
        ///Сенека.
        /// </summary>
        internal static string Rich2_106 {
            get {
                return ResourceManager.GetString("Rich2_106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самый верный путь заработать состояние - дать людям понять, что им выгодно делать вам добро. 
        ///Ж.Лабрюйер.
        /// </summary>
        internal static string Rich2_107 {
            get {
                return ResourceManager.GetString("Rich2_107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почему меня не волнуют проблемы целлюлита? Потому что журнал, в котором я мечтала бы увидеть свое фото — не Playboy, а Forbes..
        /// </summary>
        internal static string Rich2_108 {
            get {
                return ResourceManager.GetString("Rich2_108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мужчина должен зарабатывать чуть больше, чем может потратить его женщина. В противном случае они не созданы друг для друга..
        /// </summary>
        internal static string Rich2_109 {
            get {
                return ResourceManager.GetString("Rich2_109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правило номер один для того, кто хочет стать предпринимателем: никогда не устраивайся на работу ради денег.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_11 {
            get {
                return ResourceManager.GetString("Rich2_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У каждого своя черта бедности. Большинство из нас не богатеет, а просто отодвигает эту черту..
        /// </summary>
        internal static string Rich2_110 {
            get {
                return ResourceManager.GetString("Rich2_110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Человек хозяин денег, пока приобретает на них необходимое, 
        ///друг денег, пока приобретений не становится достаточно, 
        ///и раб денег, когда не может определить границу достаточного..
        /// </summary>
        internal static string Rich2_111 {
            get {
                return ResourceManager.GetString("Rich2_111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каждый решает сам… нуждается он ещё или уже достаточно богат..
        /// </summary>
        internal static string Rich2_112 {
            get {
                return ResourceManager.GetString("Rich2_112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Богат тот — кому хватает, беден тот — кому всё мало..
        /// </summary>
        internal static string Rich2_113 {
            get {
                return ResourceManager.GetString("Rich2_113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сколько раз я должен напоминать тебе, что работа не сделает тебя богатым? Сколько раз я должен напоминать тебе, что богатыми становятся в свободное от работы время?.
        /// </summary>
        internal static string Rich2_114 {
            get {
                return ResourceManager.GetString("Rich2_114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Денег не должно быть много. 
        ///Их должно быть достаточно..
        /// </summary>
        internal static string Rich2_115 {
            get {
                return ResourceManager.GetString("Rich2_115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чужих денег всегда много, своих — всегда не хватает!
        ///
        ///
        ///
        ///
        ///Живите, как если бы вы умерли завтра. Учитесь, как если бы вы жили вечно. 
        ///Махатма Ганди.
        /// </summary>
        internal static string Rich2_116 {
            get {
                return ResourceManager.GetString("Rich2_116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это своего рода забава, делать невозможное. 
        ///Уолт Дисней.
        /// </summary>
        internal static string Rich2_117 {
            get {
                return ResourceManager.GetString("Rich2_117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Когда очевидно, что цели не могут быть достигнуты, не корректируйте цели, корректируйте практические шаги.
        ///Конфуций.
        /// </summary>
        internal static string Rich2_118 {
            get {
                return ResourceManager.GetString("Rich2_118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На каждую тёмную ночь, есть яркий день. 
        ///Тупак Шакур.
        /// </summary>
        internal static string Rich2_119 {
            get {
                return ResourceManager.GetString("Rich2_119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Легко быть тем, кем ты есть сейчас
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_12 {
            get {
                return ResourceManager.GetString("Rich2_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Человек не может обнаружить новые океаны, если у него нет мужества, чтобы потерять берег из виду. 
        ///Андре Жид.
        /// </summary>
        internal static string Rich2_120 {
            get {
                return ResourceManager.GetString("Rich2_120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всегда обращайте внимание на светлую сторону жизни. 
        ///Монти Пайтон.
        /// </summary>
        internal static string Rich2_121 {
            get {
                return ResourceManager.GetString("Rich2_121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы добиться многого, мы должны не только действовать, но и мечтать, и не только планировать, но и верить. 
        ///Анатоль Франс.
        /// </summary>
        internal static string Rich2_122 {
            get {
                return ResourceManager.GetString("Rich2_122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше время ограничено, поэтому, не тратьте эту жизнь на чью-то ещё. Не попадайте в ловушку догмы – которая говорит вам жить мыслями других людей. Не позволяйте шуму чужих мнений перебить ваш внутренний голос. И, самое главное, имейте храбрость следовать своему сердцу и интуиции. Они каким-то образом уже знают, кем вы хотите стать. Всё остальное вторично. 
        ///Стив Джобс.
        /// </summary>
        internal static string Rich2_123 {
            get {
                return ResourceManager.GetString("Rich2_123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейте мужество, чтобы сказать нет, имейте мужество смотреть правде в глаза. Делайте правильные вещи, потому что это правильно. Это волшебный ключ к жизни своей полной жизнью. 
        ///В. Клемент Стоун.
        /// </summary>
        internal static string Rich2_124 {
            get {
                return ResourceManager.GetString("Rich2_124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы должны вызывать, а не ждать вдохновения, чтобы начать дело. Действие всегда порождает вдохновение. Вдохновение редко порождает действие. 
        ///Фрэнк Тиболт.
        /// </summary>
        internal static string Rich2_125 {
            get {
                return ResourceManager.GetString("Rich2_125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы воплощение информации, которую решаете принять и действовать. Чтобы изменить обстоятельства вам нужно изменить своё мышление и последующие действия. 
        ///Адлин Синлер.
        /// </summary>
        internal static string Rich2_126 {
            get {
                return ResourceManager.GetString("Rich2_126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пробуйте и терпите неудачу, но не прерывайте ваших стараний. Стивен Каггва.
        /// </summary>
        internal static string Rich2_127 {
            get {
                return ResourceManager.GetString("Rich2_127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы можете мечтать об этом, вы можете сделать это. 
        ///Уолт Дисней.
        /// </summary>
        internal static string Rich2_128 {
            get {
                return ResourceManager.GetString("Rich2_128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не слушайте тех, кто говорит вам, что вы не можете сделать то или это. Это нонсенс. Решайтесь, вы никогда не будете использовать костыли или палочку, идя на всё. Идите в школу и вступайте во все игры, которые можете. Идите туда, куда захотите. Но никогда, никогда не позволяйте другим убедить вас, что что-то сложно или невозможно. Дуглас Бадлер.
        /// </summary>
        internal static string Rich2_129 {
            get {
                return ResourceManager.GetString("Rich2_129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видеть то, чего не замечают другие, — это универсальный ключ к успеху.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_13 {
            get {
                return ResourceManager.GetString("Rich2_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставайтесь на пути, зажгите звёзды, измените мир, где бы вы ни были. 
        ///Ричард Ле Галлиенне.
        /// </summary>
        internal static string Rich2_130 {
            get {
                return ResourceManager.GetString("Rich2_130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете столкнуться с множеством поражений, но вы не должны быть побеждены. Пожалуйста, помните, что ваши трудности не определяют вас. Они просто укрепляют вашу способность преодолевать их. 
        ///Майя Анжелу.
        /// </summary>
        internal static string Rich2_131 {
            get {
                return ResourceManager.GetString("Rich2_131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Величайшая слава никогда не приходит от победы, но от роста после каждого падения. Человек определяется тем, что он хочет делать со своей жизнью, а не том, что с ним происходит. 
        ///Клей Эйкен.
        /// </summary>
        internal static string Rich2_132 {
            get {
                return ResourceManager.GetString("Rich2_132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вдохновение приходит от ежедневной работы. 
        ///Шарль Бадлер.
        /// </summary>
        internal static string Rich2_133 {
            get {
                return ResourceManager.GetString("Rich2_133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вещи, которые больше всего не хочется делать, вероятно, те, которые больше всего стоит делать. 
        ///Уинфред Холтби.
        /// </summary>
        internal static string Rich2_134 {
            get {
                return ResourceManager.GetString("Rich2_134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы делаете только то, что, как вы знаете, можете делать, вы никогда не сделаете очень многое. 
        ///Том Краузе.
        /// </summary>
        internal static string Rich2_135 {
            get {
                return ResourceManager.GetString("Rich2_135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если ваши действия вдохновляют других, мечтайте больше, узнавайте больше, делайте больше и становитесь большим, вы лидер. 
        ///Джон Куинси Адамс.
        /// </summary>
        internal static string Rich2_136 {
            get {
                return ResourceManager.GetString("Rich2_136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не бывает неудач – только опыт и ваша реакция на них. 
        ///Том Краузе.
        /// </summary>
        internal static string Rich2_137 {
            get {
                return ResourceManager.GetString("Rich2_137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доверяйте себе. Вы знаете больше, чем думаете. 
        ///Бенджамин Спок.
        /// </summary>
        internal static string Rich2_138 {
            get {
                return ResourceManager.GetString("Rich2_138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы наслаждаемся красотой бабочки, но редко признаёмся изменениям, через которые она прошла для достижения этой красоты. Майя Анжелу.
        /// </summary>
        internal static string Rich2_139 {
            get {
                return ResourceManager.GetString("Rich2_139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы считаете, что обучение стоит дорого, попробуйте узнать, сколько стоит невежество.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_14 {
            get {
                return ResourceManager.GetString("Rich2_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех — это движение от неудачи к неудачи без потери энтузиазма. Уинстон Черчилль.
        /// </summary>
        internal static string Rich2_140 {
            get {
                return ResourceManager.GetString("Rich2_140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хочешь избежать критики — ничего не делай, ничего не говори и будь никем. 
        ///Элберт Хаббард.
        /// </summary>
        internal static string Rich2_141 {
            get {
                return ResourceManager.GetString("Rich2_141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жизнь — это то, что происходит, пока вы заняты составлением планов. 
        ///Джон Леннон.
        /// </summary>
        internal static string Rich2_142 {
            get {
                return ResourceManager.GetString("Rich2_142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы сами должны стать теми переменами, которые хотим видеть в мире. 
        ///Махатма Ганди.
        /// </summary>
        internal static string Rich2_143 {
            get {
                return ResourceManager.GetString("Rich2_143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы дойти до цели, надо идти. 
        ///Оноре де Бальзак.
        /// </summary>
        internal static string Rich2_144 {
            get {
                return ResourceManager.GetString("Rich2_144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Встал поутру, умылся, привел себя в порядок — и сразу же приведи в порядок свою планету. 
        ///А. Экзюпери.
        /// </summary>
        internal static string Rich2_145 {
            get {
                return ResourceManager.GetString("Rich2_145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Считают, что успех приходит к тем, кто рано встает. Нет: успех приходит к тем, кто встает в хорошем настроении. 
        ///Марсель Ашар.
        /// </summary>
        internal static string Rich2_146 {
            get {
                return ResourceManager.GetString("Rich2_146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В начале каждой новой деятельности легкие вещи кажутся трудными, но затем трудные вещи становятся легкими. 
        ///Бодо Шеффер.
        /// </summary>
        internal static string Rich2_147 {
            get {
                return ResourceManager.GetString("Rich2_147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каждый день надо делать дело, которое тебя пугает. 
        ///Элеонора Рузвельт.
        /// </summary>
        internal static string Rich2_148 {
            get {
                return ResourceManager.GetString("Rich2_148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пытайся делать всё, что кажется невозможным.. Жизнь слишком коротка, можешь потом пожалеть...
        /// </summary>
        internal static string Rich2_149 {
            get {
                return ResourceManager.GetString("Rich2_149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы или хозяин денег, или раб денег.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_15 {
            get {
                return ResourceManager.GetString("Rich2_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жизнь полосатая, но цвета мы выбираем сами..
        /// </summary>
        internal static string Rich2_150 {
            get {
                return ResourceManager.GetString("Rich2_150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если мы не будем строить свое будущее, нам придется его терпеть..
        /// </summary>
        internal static string Rich2_151 {
            get {
                return ResourceManager.GetString("Rich2_151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех – это когда ты девять раз упал, но десять раз поднялся..
        /// </summary>
        internal static string Rich2_152 {
            get {
                return ResourceManager.GetString("Rich2_152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучший способ предсказать своё будущее – стать его создателем..
        /// </summary>
        internal static string Rich2_153 {
            get {
                return ResourceManager.GetString("Rich2_153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Большинство людей счастливы настолько, насколько они решили быть счастливыми...
        /// </summary>
        internal static string Rich2_154 {
            get {
                return ResourceManager.GetString("Rich2_154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не думай о том, правильно ли это или нет.. Делай то, что делает тебя счастливым!.
        /// </summary>
        internal static string Rich2_155 {
            get {
                return ResourceManager.GetString("Rich2_155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если ты чувствуешь, что сдаешься, вспомни, ради чего ты держался до этого..
        /// </summary>
        internal static string Rich2_156 {
            get {
                return ResourceManager.GetString("Rich2_156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Танцуй, словно тебя никто не видит, пой, словно тебя никто не слышит, люби, словно тебе не причиняли боль, и живи, словно рай уже на земле..
        /// </summary>
        internal static string Rich2_157 {
            get {
                return ResourceManager.GetString("Rich2_157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Когда кажется, что весь мир настроен против тебя – помни, что самолёт взлетает против ветра..
        /// </summary>
        internal static string Rich2_158 {
            get {
                return ResourceManager.GetString("Rich2_158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы сами рисуем свой мир. Никогда не говорите «У меня всё плохо», потому что слова, как едкие чернила въедаются в страницы книжки..
        /// </summary>
        internal static string Rich2_159 {
            get {
                return ResourceManager.GetString("Rich2_159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше будущее создается тем, что вы делаете сегодня, а не тем, что будете делать завтра.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_16 {
            get {
                return ResourceManager.GetString("Rich2_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нам не дано изменить то, что с нами уже произошло, но мы можем иначе реагировать на события..
        /// </summary>
        internal static string Rich2_160 {
            get {
                return ResourceManager.GetString("Rich2_160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поражение – это выбор! Победа тоже. Ты проиграешь, только если сам так решишь!.
        /// </summary>
        internal static string Rich2_161 {
            get {
                return ResourceManager.GetString("Rich2_161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я никогда не слушаю никого, кто критикует мои космические путешествия, мои аттракционы или моих горилл. Когда это происходит, я просто упаковываю моих динозавров и выхожу из комнаты. 
        ///Рэй Брэдбери.
        /// </summary>
        internal static string Rich2_162 {
            get {
                return ResourceManager.GetString("Rich2_162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будьте добрее, когда это возможно. А это возможно всегда. 
        ///Далай Лама.
        /// </summary>
        internal static string Rich2_163 {
            get {
                return ResourceManager.GetString("Rich2_163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваши убеждения — враги для истины опаснее, чем ложь. 
        ///Фридрих Ницше.
        /// </summary>
        internal static string Rich2_164 {
            get {
                return ResourceManager.GetString("Rich2_164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помните : каждый раз, когда вас копируют, это значит, что вы всё делаете правильно. 
        ///Salvatore Ferragamo.
        /// </summary>
        internal static string Rich2_165 {
            get {
                return ResourceManager.GetString("Rich2_165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убивая свободное время - Вы тем самым убиваете себя и своё будущее..
        /// </summary>
        internal static string Rich2_166 {
            get {
                return ResourceManager.GetString("Rich2_166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вижу цель, не вижу препятствий!.
        /// </summary>
        internal static string Rich2_167 {
            get {
                return ResourceManager.GetString("Rich2_167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завистливые люди часто осуждают то, чего не умеют, и критикуют тех, до чьего уровня им не дорасти..
        /// </summary>
        internal static string Rich2_168 {
            get {
                return ResourceManager.GetString("Rich2_168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В каждом человеке - солнце. Только дайте ему светить!.
        /// </summary>
        internal static string Rich2_169 {
            get {
                return ResourceManager.GetString("Rich2_169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Делайте то, что в глубине сердца считаете правильным, но чтобы вы не делали, вас всё равно будут осуждать. Вас будут проклинать, и если вы что-то сделаете, и если вы ничего не сделаете.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_17 {
            get {
                return ResourceManager.GetString("Rich2_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раздвиньте свои границы! Я всегда делаю то, чего я не умею, чтобы этому научиться. 
        ///Пабло Пикассо.
        /// </summary>
        internal static string Rich2_170 {
            get {
                return ResourceManager.GetString("Rich2_170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не ждите вдохновения или подходящего момента. Вдохновение существует, но оно должно приходить во время работы. 
        ///Пабло Пикассо.
        /// </summary>
        internal static string Rich2_171 {
            get {
                return ResourceManager.GetString("Rich2_171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действуйте! Откладывайте на завтра лишь то, что вы не хотите завершить до самой смерти. 
        ///Пабло Пикассо.
        /// </summary>
        internal static string Rich2_172 {
            get {
                return ResourceManager.GetString("Rich2_172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задавайте правильные вопросы! Другие увидели то, что было, и спросили, почему. Я увидел то, что могло бы быть, и спросил, почему бы нет. 
        ///Пабло Пикассо.
        /// </summary>
        internal static string Rich2_173 {
            get {
                return ResourceManager.GetString("Rich2_173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не судите, и увидите скрытую красоту! Если бы только можно было избавиться от мозга и пользоваться лишь глазами. 
        ///Пабло Пикассо.
        /// </summary>
        internal static string Rich2_174 {
            get {
                return ResourceManager.GetString("Rich2_174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Еще не слишком поздно! У юности нет возраста. 
        ///Пабло Пикассо.
        /// </summary>
        internal static string Rich2_175 {
            get {
                return ResourceManager.GetString("Rich2_175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опыт — это не то, что случается с человеком; опыт — это то, что человек делает с тем, что с ним случается..
        /// </summary>
        internal static string Rich2_176 {
            get {
                return ResourceManager.GetString("Rich2_176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Победа начинается в тот день, когда остается только одно лишь мнение - своё..
        /// </summary>
        internal static string Rich2_177 {
            get {
                return ResourceManager.GetString("Rich2_177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вам трудно? Значит, вы едете в гору!.
        /// </summary>
        internal static string Rich2_178 {
            get {
                return ResourceManager.GetString("Rich2_178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трудное — это то, что можно сделать сразу, невозможное — то, на что потребуется некоторое время..
        /// </summary>
        internal static string Rich2_179 {
            get {
                return ResourceManager.GetString("Rich2_179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Один отец говорил: «Причина, почему я не богат в том, что у меня есть вы – дети». Другой говорил: «Причина, по которой я должен быть богатым в том – что у меня есть вы».
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_18 {
            get {
                return ResourceManager.GetString("Rich2_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если проблему можно разрешить, не стоит о ней беспокоиться. Если проблема неразрешима, беспокоиться о ней бессмысленно. 
        ///Далай Лама.
        /// </summary>
        internal static string Rich2_180 {
            get {
                return ResourceManager.GetString("Rich2_180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Даже если вы очень талантливы и прилагаете большие усилия, для некоторых результатов просто требуется время: вы не получите ребенка через месяц, даже если заставите забеременеть девять женщин. 
        ///Уоррен Баффет.
        /// </summary>
        internal static string Rich2_181 {
            get {
                return ResourceManager.GetString("Rich2_181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просыпаясь утром, спроси себя: «Что я должен сделать?» Вечером, прежде чем заснуть: «Что я сделал?». 
        ///Пифагор.
        /// </summary>
        internal static string Rich2_182 {
            get {
                return ResourceManager.GetString("Rich2_182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я не терпел поражений. Я просто нашёл 10 000 способов, которые не работают. 
        ///Томас Эдисон.
        /// </summary>
        internal static string Rich2_183 {
            get {
                return ResourceManager.GetString("Rich2_183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Делай сегодня то, что другие не хотят, завтра будешь жить так, как другие не могут..
        /// </summary>
        internal static string Rich2_184 {
            get {
                return ResourceManager.GetString("Rich2_184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Между раздражителем и нашей реакцией есть промежуток. В этом промежутке лежит свобода выбора нашей реакции. От нашей реакции зависит наше развитие и наше счастье. 
        ///Стивен Кови.
        /// </summary>
        internal static string Rich2_185 {
            get {
                return ResourceManager.GetString("Rich2_185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сегодня - термин победителей. Завтра - слово неудачников. 
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_186 {
            get {
                return ResourceManager.GetString("Rich2_186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цели должны быть ясными, простыми и записанными на бумаге. Если они не записаны на бумаге и их каждый день пересматриваешь - это не цели. Это пожелания. 
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_187 {
            get {
                return ResourceManager.GetString("Rich2_187", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проблемы не решаются на уровне проблем. Анализ cамой проблемы, чтобы найти ее решение, подобен попытке восстановить свежесть листа, занимаясь листом непосредственно, в то время как решение находится в том, чтобы полить корень..
        /// </summary>
        internal static string Rich2_188 {
            get {
                return ResourceManager.GetString("Rich2_188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не ищите мотивацию для себя, становитесь мотивацией для других!.
        /// </summary>
        internal static string Rich2_189 {
            get {
                return ResourceManager.GetString("Rich2_189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Провести всю свою жизнь в страхе, так и не осуществив ни одной мечты, — вот что жестоко. Работать в поте лица за деньги и думать, что они позволят купить вещи, которые сделают вас счастливыми, — вот что страшно.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_19 {
            get {
                return ResourceManager.GetString("Rich2_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я хочу предупредить вас, что есть только одна ошибка, которую вы можете сделать. Вы можете начать истолковывать происходящее. Если вы начнете этим заниматься, все пропало. Вы попадетесь в интеллектуальную, фрейдистскую игру. Вы начнете каталогизировать интереснейшие инсайты в интеллектуальную коробочку, и, будьте уверены, не произойдет ничего реального. 
        ///Фриц Перлз.
        /// </summary>
        internal static string Rich2_190 {
            get {
                return ResourceManager.GetString("Rich2_190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Можно продолжать жить, стараться жить с положительной энергией, меньше зла извергать из себя, меньше обид. Радоваться даже при сумрачном дне. Это безумно тяжело! Безумно, и я всегда говорю: пытайтесь, пытайтесь, вырывайте себя из всей этой трясины. И летите! 
        ///Марина Голуб.
        /// </summary>
        internal static string Rich2_191 {
            get {
                return ResourceManager.GetString("Rich2_191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно, чтобы работу сделал кто-то другой, а плоды пожинали вы. Чтение книг о чьем-то духовном развитии не даст вам его постижения. Вы должны совершенствовать себя сами. 
        ///Далай-Лама.
        /// </summary>
        internal static string Rich2_192 {
            get {
                return ResourceManager.GetString("Rich2_192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если тебе не нравится то, что ты получаешь, измени то, что ты даёшь. К. Кастанеда.
        /// </summary>
        internal static string Rich2_193 {
            get {
                return ResourceManager.GetString("Rich2_193", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чудеса там, где в них верят. И чем больше в них верят, тем чаще они сбываются..
        /// </summary>
        internal static string Rich2_194 {
            get {
                return ResourceManager.GetString("Rich2_194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самая большая глупость – это делать то же самое и надеяться на другой результат..
        /// </summary>
        internal static string Rich2_195 {
            get {
                return ResourceManager.GetString("Rich2_195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Есть только один уголок во Вселенной, в улучшении которого вы можете быть уверены, и это вы сами. 
        ///Олдос Хаксли.
        /// </summary>
        internal static string Rich2_196 {
            get {
                return ResourceManager.GetString("Rich2_196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Раз дело наше новое, мы должны мыслить и действовать по-новому. 
        ///Авраам Линкольн.
        /// </summary>
        internal static string Rich2_197 {
            get {
                return ResourceManager.GetString("Rich2_197", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы рождены в мире природы; наше второе рождение – в мире духа. Бхагавадгита.
        /// </summary>
        internal static string Rich2_198 {
            get {
                return ResourceManager.GetString("Rich2_198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Никогда не отказывайтесь от своей мечты....
        /// </summary>
        internal static string Rich2_199 {
            get {
                return ResourceManager.GetString("Rich2_199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нужно сделать выбор между свободой и безопасностью. Свобода требует смелости и силы, а если у человека их нет, он теряет свободу.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_2 {
            get {
                return ResourceManager.GetString("Rich2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Умные люди — это те, которые работают с людьми умнее их самих.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_20 {
            get {
                return ResourceManager.GetString("Rich2_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настойчивость – это все. Если в вас нет желания и веры в себя, чтобы идти дальше, даже если все вокруг советуют вам бросить, вы никогда не добьетесь своего. 
        ///Тауни О&apos;Делл.
        /// </summary>
        internal static string Rich2_200 {
            get {
                return ResourceManager.GetString("Rich2_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если бы люди знали, каких трудов стоило мне мое мастерство, оно совсем не показалось бы им чудом. 
        ///Микеланджело.
        /// </summary>
        internal static string Rich2_201 {
            get {
                return ResourceManager.GetString("Rich2_201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я понял, что единственный способ добиться в жизни чего-то стоящего – упорно трудиться. Музыкант ли вы, писатель, спортсмен или бизнесмен, без труда вам не обойтись. Потрудитесь – победите, поленитесь – проиграете. 
        ///Брюс Дженнер.
        /// </summary>
        internal static string Rich2_202 {
            get {
                return ResourceManager.GetString("Rich2_202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Делать деньги – самая большоая ошибка в жизни. Делать нужно то, к чему чувствуешь склонность и талант, и если преуспеешь в этом – деньги будут. 
        ///Григ Гарсон.
        /// </summary>
        internal static string Rich2_203 {
            get {
                return ResourceManager.GetString("Rich2_203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не пытаться зарабатывать на жизнь любимым делом – самая большая ошибка людей. 
        ///Малкольм С. Форбс.
        /// </summary>
        internal static string Rich2_204 {
            get {
                return ResourceManager.GetString("Rich2_204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успех сопутствует тому, кто занимается тем, что хочет. Иного пути к успеху – нет. 
        ///Малкольм С. Форбс.
        /// </summary>
        internal static string Rich2_205 {
            get {
                return ResourceManager.GetString("Rich2_205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не позволяйте другим терроризировать себя надеждами, которые эти другие на вас возлагают. 
        ///Сью Паттон Тоэле.
        /// </summary>
        internal static string Rich2_206 {
            get {
                return ResourceManager.GetString("Rich2_206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to – Все, что у нас есть, находится в наших руках.– Но у меня в них ничего нет.– Вот о том и речь.(Все, чем мы обладаем, нам не принадлежит). 
        ///Дарий философ.
        /// </summary>
        internal static string Rich2_207 {
            get {
                return ResourceManager.GetString("Rich2_207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Алчный копит богатства как одержимый, но входит в вечную жизнь абсолютно нищим.
        ///Дарий  философ.
        /// </summary>
        internal static string Rich2_208 {
            get {
                return ResourceManager.GetString("Rich2_208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Большие деньги превращают счастливых людей в богатых. 
        ///Дмитрий Калинин.
        /// </summary>
        internal static string Rich2_209 {
            get {
                return ResourceManager.GetString("Rich2_209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если ты думаешь, что проблема во мне, тебе придется изменить меня. Если ты поймешь, что проблема в тебе, ты сможешь измениться сам, чему-то научиться и стать мудрее. Большинство людей ждут, что изменятся все остальные в мире, но только не они сами.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_21 {
            get {
                return ResourceManager.GetString("Rich2_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не важно то: сколь сыт ты, сколь одет, А важно – человек ты или нет. 
        ///Дарий  философ.
        /// </summary>
        internal static string Rich2_210 {
            get {
                return ResourceManager.GetString("Rich2_210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я обнаружил, что многие люди пользуются высокомерием для того, чтобы стараться скрывать своё невежество.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_22 {
            get {
                return ResourceManager.GetString("Rich2_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если Вы думаете, что у Вас все получится, значит так оно и будет. Если Вам кажется, что у вас ничего не выйдет, — так и случится. И в том, и в другом случае вы оказываетесь правы.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_23 {
            get {
                return ResourceManager.GetString("Rich2_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бедняки и лодыри употребляют в своей речи слово «невозможно» гораздо чаще, чем те, кто преуспевает. 
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_24 {
            get {
                return ResourceManager.GetString("Rich2_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слово «невозможно» блокирует ваш потенциал, в то время как вопрос «Как мне это сделать?» заставляет ваш мозг работать на полную катушку.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_25 {
            get {
                return ResourceManager.GetString("Rich2_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Когда дело касается денег, всегда найдется множество советчиков, у которых нет за душой и ломаного гроша.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_26 {
            get {
                return ResourceManager.GetString("Rich2_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучшая финансовая информация не всегда доступна. Надо отправиться на ее поиски.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_27 {
            get {
                return ResourceManager.GetString("Rich2_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прежде всего необходимо смотреть на ценность, а не на цену.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_28 {
            get {
                return ResourceManager.GetString("Rich2_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сегодня я богат именно благодаря тому, что я сделал в свободное время.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_29 {
            get {
                return ResourceManager.GetString("Rich2_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оправдания - это ложь, которую вы говорите самим себе. Прекратите хныкать, жаловаться и вести себя как дети. Оправдания делают человека бедным.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_3 {
            get {
                return ResourceManager.GetString("Rich2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Десятки тысяч студентов вышли из школ бизнеса, где их учили, что думать не имеет смысла.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_30 {
            get {
                return ResourceManager.GetString("Rich2_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отдаешь свои деньги в чужие руки — и они будут работать на других людей, прежде чем начнут работать на тебя.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_31 {
            get {
                return ResourceManager.GetString("Rich2_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самый ценный актив — время. Большинство людей не могут его правильно использовать. Они упорно трудятся, делая богатых богаче, но не прикладывают усилий, чтобы сделать богатыми себя.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_32 {
            get {
                return ResourceManager.GetString("Rich2_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тот наиболее богат, кто доволен малым, ибо такое довольство свидетельствует о богатстве натуры. 
        ///Сократ.
        /// </summary>
        internal static string Rich2_33 {
            get {
                return ResourceManager.GetString("Rich2_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скупец, не причитай, что плохи времена. Все, что имеешь, — трать. Запомни: жизнь одна. Сколь злата ни на грабь, а в мир иной отсюда. Не унесешь, представь, и горсточки зерна. 
        ///Омар Хайям.
        /// </summary>
        internal static string Rich2_34 {
            get {
                return ResourceManager.GetString("Rich2_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если хочешь избавиться от гостя, докучающего своими визитами, дай ему взаймы денег. 
        ///Бенджамин Франклин.
        /// </summary>
        internal static string Rich2_35 {
            get {
                return ResourceManager.GetString("Rich2_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размеры состояния определяются не величиною доходов, а привычками и образом жизни.
        /// Марк Тулий Цицерон.
        /// </summary>
        internal static string Rich2_36 {
            get {
                return ResourceManager.GetString("Rich2_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жадность до денег, если она ненасытна, гораздо тягостней нужды, ибо чем больше растут желания, тем больше потребности они порождают. 
        ///Демокрит Абдерский.
        /// </summary>
        internal static string Rich2_37 {
            get {
                return ResourceManager.GetString("Rich2_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не почитай денег ни больше, ни меньше, чем они того стоят; это хороший слуга и плохой господин. 
        ///Александр Дюма – сын.
        /// </summary>
        internal static string Rich2_38 {
            get {
                return ResourceManager.GetString("Rich2_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настоящий идеалист стремится к деньгам. Деньги — это свобода. А свобода — жизнь. 
        ///Ремарк.
        /// </summary>
        internal static string Rich2_39 {
            get {
                return ResourceManager.GetString("Rich2_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самый ценный актив - время. Большинство людей не могут его правильно использовать. Они упорно трудятся, делая богатых богаче, но не прикладывают усилий, чтобы сделать богатыми себя.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_4 {
            get {
                return ResourceManager.GetString("Rich2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деньги нужны даже для того, чтобы без них обходиться. 
        ///Оноре де Бальзак.
        /// </summary>
        internal static string Rich2_40 {
            get {
                return ResourceManager.GetString("Rich2_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деньги — это средство иметь буквально все, за исключением искреннего друга, преданной жены и здоровья. 
        ///Вебер.
        /// </summary>
        internal static string Rich2_41 {
            get {
                return ResourceManager.GetString("Rich2_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучше всего помещены те деньги, которые у нас украдены: ведь за них мы приобрели благоразумие. 
        ///Артур Шопенгауэр.
        /// </summary>
        internal static string Rich2_42 {
            get {
                return ResourceManager.GetString("Rich2_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто, обладая богатством, не уделяет от него другим и не тратит его для собственного удовольствия, тот ничем не владеет, подобно соломенному чучелу, что охраняет на поле чужое зерно. 
        ///Индийское изречение.
        /// </summary>
        internal static string Rich2_43 {
            get {
                return ResourceManager.GetString("Rich2_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Богатство — не в обладании сокровищами, а в умении его использоваться. 
        ///НаполеонI Бонапарт.
        /// </summary>
        internal static string Rich2_44 {
            get {
                return ResourceManager.GetString("Rich2_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деньги, которыми обладаешь, — орудие свободы; те, за которыми гонишься, — орудие рабства. 
        ///Ж-.Ж. Руссо.
        /// </summary>
        internal static string Rich2_45 {
            get {
                return ResourceManager.GetString("Rich2_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деньги и время — самое тяжелое бремя в жизни. Наиболее несчастны те, у кого их больше, чем они умеют использовать. 
        ///Сэмюэл Джонсон.
        /// </summary>
        internal static string Rich2_46 {
            get {
                return ResourceManager.GetString("Rich2_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цель денег — не праздность, а умножение средств для полезного служения.
        ///Генри Форд.
        /// </summary>
        internal static string Rich2_47 {
            get {
                return ResourceManager.GetString("Rich2_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если ваша единственная цель состоит в том, чтобы стать богатым, вы никогда не достигнете ее.  
        ///Джон Рокфеллер.
        /// </summary>
        internal static string Rich2_48 {
            get {
                return ResourceManager.GetString("Rich2_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деньги не сделают вас счастливее. У меня сейчас 50 миллионов, и я так же счастлив, как и тогда, когда у меня было 48 миллионов. 
        ///Арнольд Шварценеггер.
        /// </summary>
        internal static string Rich2_49 {
            get {
                return ResourceManager.GetString("Rich2_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инвестируйте время в получение знаний, затем выходите в реальный мир и пробуйте. Начинайте с малого, потому что вы будете делать ошибки. В реальном мире люди учатся на ошибках.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_5 {
            get {
                return ResourceManager.GetString("Rich2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если у вас нет денег, то займите. И никогда не занимайте мелких сумм. Занимайте сразу много, но всегда быстро отдавайте.
        ///Аристотель Онассис.
        /// </summary>
        internal static string Rich2_50 {
            get {
                return ResourceManager.GetString("Rich2_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Быть информированным означает иметь много денег. 
        ///Жак Аттали.
        /// </summary>
        internal static string Rich2_51 {
            get {
                return ResourceManager.GetString("Rich2_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Люди не хотят быть богатыми, люди хотят быть богаче других.
        ///Джон Стюарт Милль.
        /// </summary>
        internal static string Rich2_52 {
            get {
                return ResourceManager.GetString("Rich2_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какой толк от счастья? Денег на него не купишь.
        ///Хенни Янгман.
        /// </summary>
        internal static string Rich2_53 {
            get {
                return ResourceManager.GetString("Rich2_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверно считать, что люди с огромным богатством всегда счастливы.
        ///Джон Дэвисон Рокфеллер.
        /// </summary>
        internal static string Rich2_54 {
            get {
                return ResourceManager.GetString("Rich2_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Богат не тот, у кого много денег, а кому хватает, счастлив не тот, кто владеет всем, а тот, кто имеет то, что купить нельзя, любим не тот, кто красив лицом, а тот, кого ценят за душу..
        /// </summary>
        internal static string Rich2_55 {
            get {
                return ResourceManager.GetString("Rich2_55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Процветание — это не материя. Это установка сознания и жизненный принцип. 
        ///Рэнди Гейдж.
        /// </summary>
        internal static string Rich2_56 {
            get {
                return ResourceManager.GetString("Rich2_56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самый бедный человек не тот, у которого нет ни гроша в кармане, а тот, у которого нет мечты. 
        ///Сократ.
        /// </summary>
        internal static string Rich2_57 {
            get {
                return ResourceManager.GetString("Rich2_57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Благословенны трудности, ибо ими растём. Надо быть благодарными любой жизненной трудности. Она заставляет нас проявлять волю и осваивать почву своих богатых возможностей. 
        ///Николай Рерих.
        /// </summary>
        internal static string Rich2_58 {
            get {
                return ResourceManager.GetString("Rich2_58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удивительно устроен человек - он огорчается, когда теряет богатство, и равнодушен к тому, что безвозвратно уходят дни его жизни. 
        ///Абу-ль-Фарадж.
        /// </summary>
        internal static string Rich2_59 {
            get {
                return ResourceManager.GetString("Rich2_59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Великие возможности видят не глазами. Их видят умом.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_6 {
            get {
                return ResourceManager.GetString("Rich2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Человек живет на земле не для того, чтобы стать богатым, но для того, чтобы стать счастливым. 
        ///Стендаль.
        /// </summary>
        internal static string Rich2_60 {
            get {
                return ResourceManager.GetString("Rich2_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лучше быть достойным человеком под убогой одеждой, чем бесчестно жить в богатом наряде. 
        ///Эзоп.
        /// </summary>
        internal static string Rich2_61 {
            get {
                return ResourceManager.GetString("Rich2_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чем меньше человеку нужно, тем ближе он к богам. 
        ///Сократ.
        /// </summary>
        internal static string Rich2_62 {
            get {
                return ResourceManager.GetString("Rich2_62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наживи себе такое богатство, чтобы никто не смог отнять его у тебя, чтобы оно и после смерти осталось с тобой. Богатство это - твоя душа (древнеиндийская мудрость)..
        /// </summary>
        internal static string Rich2_63 {
            get {
                return ResourceManager.GetString("Rich2_63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работая только ради материальных благ, мы сами себе строим тюрьму. И запираемся в одиночестве, и все наши богатства - прах и пепел, они бессильны доставить нам то, ради чего стоит жить. 
        ///Антуан де Сент Экзюпери.
        /// </summary>
        internal static string Rich2_64 {
            get {
                return ResourceManager.GetString("Rich2_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Об уровне жизни не свидетельствует богатый дом, а также наличие автомобиля. Любая техника всё равно однажды сломается, и когда-нибудь обязательно наступит кризис. Высокий уровень жизни на самом деле не что иное, как высокий уровень мышления. 
        ///Геше Джампа Тинлей.
        /// </summary>
        internal static string Rich2_65 {
            get {
                return ResourceManager.GetString("Rich2_65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ищи знание. Если ты впадёшь в бедность, оно станет твоим богатством; а если разбогатеешь - оно украсит тебя. 
        ///Аль-Зубаер.
        /// </summary>
        internal static string Rich2_66 {
            get {
                return ResourceManager.GetString("Rich2_66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Когда вы богаты - используйте богатство. Когда бедны - используйте нищету. Будьте практичны. 
        ///Ошо
        ///
        ///Нас учит бедность жизненному опыту. 
        ///Публий.
        /// </summary>
        internal static string Rich2_67 {
            get {
                return ResourceManager.GetString("Rich2_67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вещи, которыми ты владеешь, в конце концов, начинают владеть тобой. Высшее богатство — отсутствие жадности. 
        ///Сенека.
        /// </summary>
        internal static string Rich2_68 {
            get {
                return ResourceManager.GetString("Rich2_68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жадность до денег, если она ненасытна, гораздо тягостней нужды, ибо чем больше растут желания, тем большие потребности они порождают. 
        ///Демокрит.
        /// </summary>
        internal static string Rich2_69 {
            get {
                return ResourceManager.GetString("Rich2_69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Многие люди верят в Бога, но их действия показывают, что они не доверяют Богу.
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_7 {
            get {
                return ResourceManager.GetString("Rich2_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В этом мире богатыми нас делает не то, что мы получаем, а то, что мы отдаём.
        ///Генри Бигер.
        /// </summary>
        internal static string Rich2_70 {
            get {
                return ResourceManager.GetString("Rich2_70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тот, кто никогда не искал ни дружбы, ни любви, в тысячу раз беднее того, кто их обеих утратил. 
        ///Жан Поль.
        /// </summary>
        internal static string Rich2_71 {
            get {
                return ResourceManager.GetString("Rich2_71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В своей жизни мы можем найти себе оправдание, а можем - здоровье, любовь, понимание, приключение, богатство и счастье. 
        ///Ричард Бах.
        /// </summary>
        internal static string Rich2_72 {
            get {
                return ResourceManager.GetString("Rich2_72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изобилие - это ваше внутреннее состояние ума. Если вы смотрите только на &quot;нехватку&quot;, то это будет увеличиваться в вашей жизни. Но посмотрите на то, что вы имеете, и тогда изобилие увеличится. 
        ///Шри Шри Рави Шанкар.
        /// </summary>
        internal static string Rich2_73 {
            get {
                return ResourceManager.GetString("Rich2_73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всё дело в мыслях к нашей жизни, нашего отношения к ней. Давно замечено - кто больше говорит о болезнях - больше болеет, кто больше говорит о богатстве - богат 
        ///(фильм &quot;Секрет&quot;)..
        /// </summary>
        internal static string Rich2_74 {
            get {
                return ResourceManager.GetString("Rich2_74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все состоит в воображении. Последуй природе, никогда не будешь беден. Последуй людским мнениям, никогда богат не будешь. Фонвизин Д. И..
        /// </summary>
        internal static string Rich2_75 {
            get {
                return ResourceManager.GetString("Rich2_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы способны видеть, ходить, любить и каждое утро вставать с постели, вы - сказочно богатый человек! 
        ///Джеймс Рэй, автор книги &quot;Законы успеха&quot;.
        /// </summary>
        internal static string Rich2_76 {
            get {
                return ResourceManager.GetString("Rich2_76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Богатства существуют, чтобы их тратить, а траты - чтобы делать добро и этим снискать честь.
        ///Фрэнсис Бэкон.
        /// </summary>
        internal static string Rich2_77 {
            get {
                return ResourceManager.GetString("Rich2_77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подлинное богатство человека — это богатство человеческих ошибок, накопленный тысячелетиями жизненный опыт.
        ///Хосе Ортега-и-Гассет.
        /// </summary>
        internal static string Rich2_78 {
            get {
                return ResourceManager.GetString("Rich2_78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мало кто из нас может вынести бремя богатства. Конечно, чужого.
        ///Марк Твен.
        /// </summary>
        internal static string Rich2_79 {
            get {
                return ResourceManager.GetString("Rich2_79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страсть — это начало успеха!
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_8 {
            get {
                return ResourceManager.GetString("Rich2_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Есть люди настолько скупые, будто они собираются жить вечно. Есть настолько расточительные - будто они собираются умирать завтра. 
        ///Аристотель.
        /// </summary>
        internal static string Rich2_80 {
            get {
                return ResourceManager.GetString("Rich2_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Богатство измеряется не цифрами, а ощущениями. Богат не тот, у кого много денег, а тот, кому их хватает..
        /// </summary>
        internal static string Rich2_81 {
            get {
                return ResourceManager.GetString("Rich2_81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деньги - это аккумулированные возможности..
        /// </summary>
        internal static string Rich2_82 {
            get {
                return ResourceManager.GetString("Rich2_82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Человек приходит в этот мир без ничего, и уходит из него ни с чем, а всю свою жизнь тратит на накопление..
        /// </summary>
        internal static string Rich2_83 {
            get {
                return ResourceManager.GetString("Rich2_83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я уже вышел из того возраста, когда любимым делом можно заниматься только из энтузиазма, ничего при этом не зарабатывая. 
        ///А.Ситнянский.
        /// </summary>
        internal static string Rich2_84 {
            get {
                return ResourceManager.GetString("Rich2_84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кто хочет разбогатеть в течении дня, будет повешен в течении года. 
        ///Леонардо да Винчи.
        /// </summary>
        internal static string Rich2_85 {
            get {
                return ResourceManager.GetString("Rich2_85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Денег не хватает всем!!! Одному на корку хлеба, другому на &quot;Мерседес&quot;, третьему на покупку завода &quot;Норильский никель&quot;..
        /// </summary>
        internal static string Rich2_86 {
            get {
                return ResourceManager.GetString("Rich2_86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Банк - это место, где вам одолжат денег, если вы докажете, что они вам не нужны. 
        ///Боб Хоуп.
        /// </summary>
        internal static string Rich2_87 {
            get {
                return ResourceManager.GetString("Rich2_87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Щедрость не в том, чтобы давать много, а в том, чтобы дать своевременно. 
        ///Лабрюйер.
        /// </summary>
        internal static string Rich2_88 {
            get {
                return ResourceManager.GetString("Rich2_88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Единственное преимущество иметь деньги, заключается в возможности их тратить. 
        ///Б.Франклин.
        /// </summary>
        internal static string Rich2_89 {
            get {
                return ResourceManager.GetString("Rich2_89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бедный, неудачный, несчастливый и нездоровый это тот, кто часто использует слово «завтра».
        ///Роберт Кийосаки.
        /// </summary>
        internal static string Rich2_9 {
            get {
                return ResourceManager.GetString("Rich2_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Богатство - враг изобретательности..
        /// </summary>
        internal static string Rich2_90 {
            get {
                return ResourceManager.GetString("Rich2_90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деньги портят человека, а инфляция портит деньги. 
        ///Борис Крутиер.
        /// </summary>
        internal static string Rich2_91 {
            get {
                return ResourceManager.GetString("Rich2_91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корысть умеет говорить на любых языках, в том числе и бескорыстия..
        /// </summary>
        internal static string Rich2_92 {
            get {
                return ResourceManager.GetString("Rich2_92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказ - это предложение поднять цену. 
        ///Жорж Элгози.
        /// </summary>
        internal static string Rich2_93 {
            get {
                return ResourceManager.GetString("Rich2_93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Люди почему - то верят, что можно быть богатым, не уподобляясь богатым. 
        ///Логан Смит.
        /// </summary>
        internal static string Rich2_94 {
            get {
                return ResourceManager.GetString("Rich2_94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хочешь быть богатым, не увеличивай своё состояние - уменьшай свою жадность. 
        ///Гельвеций.
        /// </summary>
        internal static string Rich2_95 {
            get {
                return ResourceManager.GetString("Rich2_95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Богат тот, кто получает больше, чем тратит. 
        ///Лабрюйер.
        /// </summary>
        internal static string Rich2_96 {
            get {
                return ResourceManager.GetString("Rich2_96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скупость - дальше от бережливости, даже чем расточительность. 
        ///Ларошфуко.
        /// </summary>
        internal static string Rich2_97 {
            get {
                return ResourceManager.GetString("Rich2_97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трать на пенс меньше, чем зарабатываешь. 
        ///Франклин.
        /// </summary>
        internal static string Rich2_98 {
            get {
                return ResourceManager.GetString("Rich2_98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Люди считающие, что деньги могут сделать всё, сами способны сделать всё ради денег. 
        ///Буаст.
        /// </summary>
        internal static string Rich2_99 {
            get {
                return ResourceManager.GetString("Rich2_99", resourceCulture);
            }
        }
    }
}
