//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daruma.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CitationLocalizationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CitationLocalizationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Daruma.Resources.CitationLocalizationResources", typeof(CitationLocalizationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaa.
        /// </summary>
        public static string aaa {
            get {
                return ResourceManager.GetString("aaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bbb.
        /// </summary>
        public static string bbb {
            get {
                return ResourceManager.GetString("bbb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ccc.
        /// </summary>
        public static string ccc {
            get {
                return ResourceManager.GetString("ccc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  some citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome citationsome [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Citaion1 {
            get {
                return ResourceManager.GetString("Citaion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd.
        /// </summary>
        public static string ddd {
            get {
                return ResourceManager.GetString("ddd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eee.
        /// </summary>
        public static string eee {
            get {
                return ResourceManager.GetString("eee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fff.
        /// </summary>
        public static string fff {
            get {
                return ResourceManager.GetString("fff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ggg.
        /// </summary>
        public static string ggg {
            get {
                return ResourceManager.GetString("ggg", resourceCulture);
            }
        }
    }
}
